-- AutoArt brand_objects (brand_id=3). 290 products; image_source: https://us.autoartmodels.com/
INSERT INTO brand_objects (brand_id, name_en, name_zh, image_url, image_source, release_price_cny, release_price_usd, release_date, category_en, category_zh, scale) VALUES
(3, 'TOYOTA CENTURY GRMN (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/78763w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SENNA GTR (ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/81956w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SRT HELLCAT REDEYE JAILBREAK (F8 GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/71752w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SRT HELLCAT REDEYE JAILBREAK (KNUCKLE WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71751w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS ( RIVIERA BLUE )', NULL, 'http://localhost:9000/minicollections-media/autoart/78182w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS ( MINT GREEN )', NULL, 'http://localhost:9000/minicollections-media/autoart/78181w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SRT HELLCAT REDEYE JAILBREAK (PITCH BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/71754w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SENNA GTR (ONYX BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/81954w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS ( CRAYON )', NULL, 'http://localhost:9000/minicollections-media/autoart/78180w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, '1/18 McLAREN SENNA GTR (SILICA WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/81953w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS WEISSACH PACKAGE ( LIZARD GREEN )', NULL, 'http://localhost:9000/minicollections-media/autoart/78179w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SRT HELLCAT REDEYE JAILBREAK (B5 BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71753w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS WEISSACH PACKAGE ( RACING YELLOW )', NULL, 'http://localhost:9000/minicollections-media/autoart/78178w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS WEISSACH PACKAGE ( LAVA ORANGE )', NULL, 'http://localhost:9000/minicollections-media/autoart/78177w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD F-150 RAPTOR SUPERCREW 2019 (RUBY RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/72948w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SCAT PACK WIDEBODY (SUBLIME)', NULL, 'http://localhost:9000/minicollections-media/autoart/71758w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SCAT PACK WIDEBODY (PLUM CRAZY)', NULL, 'http://localhost:9000/minicollections-media/autoart/71757w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT SUPER STOCK 2023 (FROSTBITE/BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71767w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT JAILBREAK 2022 (INDIGO BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71763w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SCAT PACK WIDEBODY (DESTROYER GREY)', NULL, 'http://localhost:9000/minicollections-media/autoart/71756w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'FORD F-150 RAPTOR SUPERCREW 2019 (VELOCITY BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72949w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT SUPER STOCK 2023 (SUBLIME/GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/71769w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT SUPER STOCK 2023 (PLUM CRAZY/PURPLE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71768w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT JAILBREAK 2022 (F8 GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/71761w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'FORD F-150 RAPTOR SUPERCREW 2019 (AGATE BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/72947w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA SPRINTER TRUENO (AE86) INITIAL D PROJECT D FINAL VERSION (30th ANNIVERSARY)', NULL, 'http://localhost:9000/minicollections-media/autoart/78787w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD F-150 RAPTOR SUPERCREW 2019 (OXFORD WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72946w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT JAILBREAK 2022 (HELLRAISIN/PURPLE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71762w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN FAIRLADY Z WANGAN MIDNIGHT', NULL, 'http://localhost:9000/minicollections-media/autoart/77453w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER SRT JAILBREAK 2022 (TORRED)', NULL, 'http://localhost:9000/minicollections-media/autoart/71764w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO GTR (MONTEREY BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79135w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN FAIRLADY Z WANGAN MIDNIGHT AKUMA no Z (COMIC #4 VERSION)', NULL, 'http://localhost:9000/minicollections-media/autoart/20686a.jpg', 'https://us.autoartmodels.com/', NULL, 33, NULL, 'car', NULL, '1:64'),
(3, 'NISSAN FAIRLADY Z WANGAN MIDNIGHT AKUMA no Z (COMIC #1 VERSION)', NULL, 'http://localhost:9000/minicollections-media/autoart/20685a.jpg', 'https://us.autoartmodels.com/', NULL, 33, NULL, 'car', NULL, '1:64'),
(3, 'PORSCHE 911(930) TURBO WANGAN MIDNIGHT BLACKBIRD (COMIC #1 VERSION)', NULL, 'http://localhost:9000/minicollections-media/autoart/20636a.jpg', 'https://us.autoartmodels.com/', NULL, 33, NULL, 'car', NULL, '1:64'),
(3, 'DODGE CHALLENGER SRT SUPER STOCK 2023 (PITCH BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/71765w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO GTR (ARANCIO ISHTAR)', NULL, 'http://localhost:9000/minicollections-media/autoart/79139w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO GTR (IMPACT WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79136w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO GTR (SUPERFLY YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79138w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO GTR (DEEP BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/79137w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-AMG G63 2019 (IRIDIUM SILVER METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/76358w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (CYBER ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/73099w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (ICONIC SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/73096w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (ERUPTION GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/73097w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (OXFORD WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/73095w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-AMG G63 2017 (SUNSET BEAM)', NULL, 'http://localhost:9000/minicollections-media/autoart/20202x.jpg', 'https://us.autoartmodels.com/', NULL, 30, NULL, 'car', NULL, '1:64'),
(3, 'PORSCHE 911 (930) TURBO WANGAN MIDNIGHT', NULL, 'http://localhost:9000/minicollections-media/autoart/78158w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-AMG G 63 2017 (SOLAR BEAM)', NULL, 'http://localhost:9000/minicollections-media/autoart/20201x.jpg', 'https://us.autoartmodels.com/', NULL, 30, NULL, 'car', NULL, '1:64'),
(3, 'MERCEDES-AMG G63 2019 (EMERALD GREEN METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/76355w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-AMG G63 2019 (BRILLIANT BLUE METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/76359w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-AMG G63 2019 (DESIGNO CARDINAL RED METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/76353w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA 2000GT 1967 (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/79548x.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA 2000GT 1967 (RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/79547x.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R50 BY ITALDESIGN (METALLIC GREEN / BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/77512w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (GRABBER BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/73094w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R50 BY ITALDESIGN (METALLIC RED / GOLD)', NULL, 'http://localhost:9000/minicollections-media/autoart/77514w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA 2000GT 1967 (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79546w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R50 BY ITALDESIGN (BLACK/MATT BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/77513w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA SPRINTER TRUENO (AE86)', NULL, 'http://localhost:9000/minicollections-media/autoart/20031a-.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'HONDA NSR500 WGP500 GUN KOMA #56 BARIBARI LEGEND', NULL, 'http://localhost:9000/minicollections-media/autoart/12566a.jpg', 'https://us.autoartmodels.com/', NULL, 215, NULL, 'car', NULL, '1:12'),
(3, 'PORSCHE 911 CARRERA 2.7 RS (VIPER GREEN/BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/78034w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R50 BY ITALDESIGN (METALLIC WHITE / BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/77511w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 CARRERA 2.7 RS (GULF BLUE/BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/78032w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 CARRERA 2.7 RS (LIGHT YELLOW/GREEN STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/78033w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 CARRERA 2.7 RS (GRAND PRIX WHITE/GREEN STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/78031w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG ONE : 1 (CLEAR CARBON FIBER/GOLD STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/20043a.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'KOENIGSEGG ONE : 1 (PEBBLE WHITE/CARBON BLACK /RED ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/20041x.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'PORSCHE 911 CARRERA 2.7 RS (GRAND PRIX WHITE/RED STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/78030w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG ONE : 1 (MOON GREY/CARBON BLACK /ORANGE ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/20042x.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'KOENIGSEGG ONE : 1 (LAVA ORANGE/CARBON FIBER/SILVER ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/20044x.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'NISSAN GT-R50 BY ITALDESIGN (GREY / GOLD)', NULL, 'http://localhost:9000/minicollections-media/autoart/77510w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 CARRERA 2.7 RS', NULL, 'http://localhost:9000/minicollections-media/autoart/78026a.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB5 (CARIBBEAN PEARL/BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/70288w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION (RED/ CARBON BONNET) *Online Exclusive*', NULL, 'http://localhost:9000/minicollections-media/autoart/77479w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION (WHITE/ CARBON BONNET) *Online Exclusive*', NULL, 'http://localhost:9000/minicollections-media/autoart/77478w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB5 (DUBONNET ROSSO/RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/70289w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'CLEAR COVER & BASE PLATE SET (LBWK/GOLD)', NULL, 'http://localhost:9000/minicollections-media/autoart/90038-01.jpg', 'https://us.autoartmodels.com/', NULL, 43, NULL, 'car', NULL, '1:18'),
(3, 'CLEAR COVER & BASE PLATE SET (LBWK/GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/90037-01.jpg', 'https://us.autoartmodels.com/', NULL, 43, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB5 (BIRCH SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/70287w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/77466w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION  (RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/77468w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION  (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/77467w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'CLEAR COVER & BASE PLATE SET (SEIBU KEISATSU SUPER Z)', NULL, 'http://localhost:9000/minicollections-media/autoart/90039-01.jpg', 'https://us.autoartmodels.com/', NULL, 43, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 JOTA (IMPACT WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79145w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB5', NULL, 'http://localhost:9000/minicollections-media/autoart/70296w-.jpg', 'https://us.autoartmodels.com/', NULL, 325, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 918 SPYDER WEISSACH PACKAGE (ACID GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/77921w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB5 (BRITISH RACING GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/70286w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 (VERDE MIC/METALLIC GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/79150w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 JOTA (SUPERFLY YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79144w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C8 STINGRAY Z51 (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/71280x.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 720S (VOLCANO YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/76070w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C8 STINGRAY Z51 (CERAMIC MATRIX GREY METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/71284w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C8 STINGRAY Z51 (SEBRING ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71283w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C8 STINGRAY Z51 (TORCH RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/71282w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C8 STINGRAY Z51 (RAPID BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71281w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI MIURA SVR', NULL, 'http://localhost:9000/minicollections-media/autoart/79171w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN HONDA MP4/6 JAPANESE GP 1991 A.SENNA #1', NULL, 'http://localhost:9000/minicollections-media/autoart/89150w-.jpg', 'https://us.autoartmodels.com/', NULL, 325, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R (R35) NISMO 2022 SPECIAL EDITION (NISMO STEALTH GRAY)', NULL, 'http://localhost:9000/minicollections-media/autoart/77505w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R (R35) NISMO 2022 SPECIAL EDITION (ULTIMATE METAL SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/77503w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R (R35) NISMO 2022 SPECIAL EDITION (VIBRANT RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/77502w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'NISMO R34 GT-R Z-TUNE (BAYSIDE BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/77462w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER R/T SCAT PACK WIDEBODY 2022 (SMOKE SHOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/71774w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) LIMITED EDITION (SUNLIGHT YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/73225w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'NISMO R34 GT-R Z-TUNE (Z-TUNE SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/77461w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER R/T SCAT PACK WIDEBODY 2022 (SINAMON STICK)', NULL, 'http://localhost:9000/minicollections-media/autoart/71773w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER R/T SCAT PACK WIDEBODY 2022 (INDIGO BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71772w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHALLENGER R/T SCAT PACK WIDEBODY 2022 (HELLRAISIN)', NULL, 'http://localhost:9000/minicollections-media/autoart/71771w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C7 ZR1 (SEBRING ORANGE TINTCOAT)', NULL, 'http://localhost:9000/minicollections-media/autoart/71279w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C7 ZR1 (ARCTIC WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/71270w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C7 ZR1 (CORVETTE RACING YELLOW TINTCOAT)', NULL, 'http://localhost:9000/minicollections-media/autoart/71278w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C7 ZR1 (CERAMIC MATRIX GREY METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/71277w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE C7 ZR1 (GLOSS BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/71276w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) 2021 (RACING BLUE PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/73224w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) 2021 (FLAME RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/73223w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) 2021 (POLISHED METAL METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/73221w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN HONDA MP4/6 JAPANESE GP 1991 A.SENNA #1 (WITH McLAREN LOGO)', NULL, 'http://localhost:9000/minicollections-media/autoart/89140w-.jpg', 'https://us.autoartmodels.com/', NULL, 325, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) 2021 (CHAMPIONSHIP WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/73220w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CIVIC TYPE R (FK8) 2021 (CRYSTAL BLACK PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/73222w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI AVENTADOR SVJ (ARANCIO ATLAS/PEARL ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79218w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB SILHOUETTE WORKS HURACAN GT (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/79129w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SPEEDTAIL (SUPERNOVA SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/76090w-.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SPEEDTAIL (LANTANA PURPLE)', NULL, 'http://localhost:9000/minicollections-media/autoart/76089w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CENTURY OPEN CAR (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/79531w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB SILHOUETTE WORKS HURACAN GT (RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/79126w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB SILHOUETTE WORKS HURACAN GT (PEARL GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/79128x.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB SILHOUETTE WORKS HURACAN GT (METALLIC YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79127w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SPEEDTAIL (VOLCANO ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/76088w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SPEEDTAIL (VOLCANO RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/76087w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB SILHOUETTE WORKS HURACAN GT (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79125w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT2 RS WEISSACH PACKAGE (ACID GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/78187w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI HURACAN EVO (ROSSO BIA)', NULL, 'http://localhost:9000/minicollections-media/autoart/79213w-.jpg', 'https://us.autoartmodels.com/', NULL, 210, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT HERITAGE EDITION ALAN MANN (RED W/ GOLD STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/72927w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI HURACAN EVO (ARANCIO XANTO)', NULL, 'http://localhost:9000/minicollections-media/autoart/79214w-.jpg', 'https://us.autoartmodels.com/', NULL, 210, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT HERITAGE EDITION HOLMAN MOODY (GOLD W/ RED & WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72928w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT HERITAGE EDITION PROTOTYPE (WIMBLEDON WHITE W/ ANTIMATTER BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72926w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CELICA LIFTBACK 2000GT (RA25) 1973 (DARK PURPLE METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/78769w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'LOTUS EUROPA SPECIAL', NULL, 'http://localhost:9000/minicollections-media/autoart/75396w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CELICA LIFTBACK 2000GT (RA25) 1973 (MOSS GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/78768w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI URUS (ROSSO EFESTO/PEARL RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/79170w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SV-R (IMPACT WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79149w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SV-R (BLU LE MANS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79148w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (MATT BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/78852w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SV-R (SUPERFLY YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79147w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (PASSIONATE PINK)', NULL, 'http://localhost:9000/minicollections-media/autoart/78859w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (PEARL RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/78853w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (WHITEST WHITE/CARBON BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/78851w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SV-R (DEEP BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/79146w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (PEARL BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/78858w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 (DEEP BLACK METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/79159w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (PEARL YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/78854w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CB750F BARIBARI LEGEND', NULL, 'http://localhost:9000/minicollections-media/autoart/12561-17.jpg', 'https://us.autoartmodels.com/', NULL, 200, NULL, 'car', NULL, '1:12'),
(3, 'LAMBORGHINI DIABLO SE30 (VIOLA SE30/METALLIC PURPLE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79158a.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LFA (WHITEST WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/78850a.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 (GIALLO SPYDER/METALLIC YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79157a.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 (BLU SIRENA/METALLIC BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79156w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (METALLIC WHITE/CARBON BONNET)', NULL, 'http://localhost:9000/minicollections-media/autoart/79241w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CENTURY SPECIAL EDITION WITH CURTAIN (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/78770w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CENTURY SPECIAL EDITION WITH CURTAIN (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/78765w.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2019 R.BRISCOE/R.WESTBROOK/S.DIXON #69', NULL, 'http://localhost:9000/minicollections-media/autoart/81913w-.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2019 J.HAND/D.MULLER/S.BOURDAIS #68', NULL, 'http://localhost:9000/minicollections-media/autoart/81912w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT2 RS WEISSACH PACKAGE ( MIAMI BLUE )', NULL, 'http://localhost:9000/minicollections-media/autoart/78175w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2019 A.PRIAULX/H.TINCKNELL/J.BOMARITO #67', NULL, 'http://localhost:9000/minicollections-media/autoart/81911w-.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2019 S.MUCKE/O.PLA/B.JOHNSON #66', NULL, 'http://localhost:9000/minicollections-media/autoart/81910w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 JOTA (TITANIO/METALLIC SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/79143w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI DIABLO SE30 JOTA (VIOLA SE30/METALLIC PURPLE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79142w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911(991) GT2 RS (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/78171w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA CENTURY GRMN (PEARL WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/78764w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(PURE WHITE PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/78505w-.jpg', 'https://us.autoartmodels.com/', NULL, 215, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(BLUISH BLACK PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/78503w-.jpg', 'https://us.autoartmodels.com/', NULL, 215, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(PURE WHITE PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/78511w-.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(CHIFFON IVORY METALLIC/ BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78510w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(JUNGLE GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/78509w-.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(BLUISH BLACK PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/78508w.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(BRISK BLUE METALLIC / BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78507w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY SIERRA (JB74)(KINETIC YELLOW / BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78506w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 SS (NERO VERNICE/BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/70919w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 SS (GRIGIO METALIZZATTO/SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/70916w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 SS (FRENCH RACING BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/70917w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 SS (GIALLO BUGATTI/YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/70918w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(JUNGLE GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/78504w-.jpg', 'https://us.autoartmodels.com/', NULL, 180, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(CHIFFON IVORY METALLIC/ BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78500w.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 LM LE MANS 24HR 1994 #34', NULL, 'http://localhost:9000/minicollections-media/autoart/89417w-.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(BRISK BLUE METALLIC / BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78502w-.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SENNA (TROPHY KYANOS/BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/76079w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 600LT (VOLCANO RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/76085w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 600LT (MYAN ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/76084w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'SUZUKI JIMNY (JB64)(KINETIC YELLOW / BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/78501w.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 600LT (SICILIAN YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/76082w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SENNA (TROPHY MIRA/ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/76078w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/77472w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/77471w-.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN SENNA (STEALTH COSMOS/BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/76076w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI AVENTADOR SVJ  (GIALLO TENERIFE/PEARL YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/79175w-.jpg', 'https://us.autoartmodels.com/', NULL, 300, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (MARTINI LIVERY)', NULL, 'http://localhost:9000/minicollections-media/autoart/79185w.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN SKYLINE GT-R (R34) V-SPEC II (WHITE PEARL)', NULL, 'http://localhost:9000/minicollections-media/autoart/77406w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (MATT METALLIC SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/79181w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD SHELBY GT-350R  (FURY ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72929w-.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT 2017 (INGOT SILVER/BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/12108w.jpg', 'https://us.autoartmodels.com/', NULL, 470, NULL, 'car', NULL, '1:12'),
(3, '1/12 FORD GT 2017 (LIQUID RED/SILVER STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/12106w-.jpg', 'https://us.autoartmodels.com/', NULL, 470, NULL, 'car', NULL, '1:12'),
(3, 'ASTON MARTIN VANTAGE 2019 (HYPER RED/CARBON BLACK ROOF)', NULL, 'http://localhost:9000/minicollections-media/autoart/70277w-.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (HYPER RED/GOLD ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79182w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI CENTENARIO (ARANCIO ARGOS/PEARL ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79201w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (HYPER BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/79183w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE 2019 (JET BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/70275w.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG AGERA RS (CHILLI RED/CARBON BLACK/BLACK ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79022-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI URUS (GRIGIO TITANS/MATT GREY)', NULL, 'http://localhost:9000/minicollections-media/autoart/79164a.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG AGERA RS (CONE ORANGE/CARBON BLACK/BLACK ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79023-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'LIBERTY WALK LB-WORKS LAMBORGHINI AVENTADOR LIMITED EDITION (GLOSS BLACK/GOLD ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79184w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI 57SC ATLANTIC 1938 (BLUE/WITH METAL WIRE-SPOKE WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/50947a.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:43'),
(3, 'BUGATTI 57SC ATLANTIC 1938 (BLACK/WITH DISC WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/50946a.jpg', 'https://us.autoartmodels.com/', NULL, 225, NULL, 'car', NULL, '1:43'),
(3, 'DODGE CHALLENGER SRT HELLCAT WIDEBODY 2018 (YELLOW JACKET/SATIN BLACK PAINTED HOOD)', NULL, 'http://localhost:9000/minicollections-media/autoart/71737w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA ROADSTER (BLU TRICOLORE CARBON FIBER)', NULL, 'http://localhost:9000/minicollections-media/autoart/78286a.jpg', 'https://us.autoartmodels.com/', NULL, 400, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA ROADSTER (ROSSO MONZA/RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/78287-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG REGERA (WHITE/BLACK CARBON/RED ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/79027-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG REGERA (CANDY RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/79026-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LS 500h (SONIC WHITE METALLIC/CRIMSON & BLACK INTERIOR)', NULL, 'http://localhost:9000/minicollections-media/autoart/78866w.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LS 500h (MANGANESE LUSTER METALLIC/CRIMSON & BLACK INTERIOR)', NULL, 'http://localhost:9000/minicollections-media/autoart/78867w-.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CAMARO ZL1 2017 (BRIGHT YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/71205w-.jpg', 'https://us.autoartmodels.com/', NULL, 190, NULL, 'car', NULL, '1:18'),
(3, 'Lexus LS 500h (black/black interior)', NULL, 'http://localhost:9000/minicollections-media/autoart/78868w.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE GT3 TEAM R-MOTORSPORT BATHURST 12 HOUR  2019 J.DENNIS/M.VAXIVIERE/M.KIRCHHOEFER #62', NULL, 'http://localhost:9000/minicollections-media/autoart/81906a.jpg', 'https://us.autoartmodels.com/', NULL, 200, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE GTE LE MANS PRO 2018 LYNN/MARTIN/ADAM #97', NULL, 'http://localhost:9000/minicollections-media/autoart/81809a.jpg', 'https://us.autoartmodels.com/', NULL, 190, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE GTE LE MANS PRO 2018 SORENSEN/THIIM/TURNER #95', NULL, 'http://localhost:9000/minicollections-media/autoart/81808w.jpg', 'https://us.autoartmodels.com/', NULL, 190, NULL, 'car', NULL, '1:18'),
(3, 'DODGE VIPER ACR 2017 (COMPETITION BLUE W/ BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/71734a.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'DODGE VIPER ACR 2017 (BILLET SILVER METALLIC W/ BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/71733a.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE GTE LE MANS PRO 2018 PRESENTATION CAR (GREEN WITH STRIPES/A)', NULL, 'http://localhost:9000/minicollections-media/autoart/81807w-.jpg', 'https://us.autoartmodels.com/', NULL, 165, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VANTAGE GTE LE MANS PRO 2018 (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/81806w.jpg', 'https://us.autoartmodels.com/', NULL, 150, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2016 R.BRISOE/S.DIXON/R.WESTBROOK #69', NULL, 'http://localhost:9000/minicollections-media/autoart/81612w-.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2017 P.DERANI/A.PRIAULX/H.TINCKNELL #67', NULL, 'http://localhost:9000/minicollections-media/autoart/81710a.jpg', 'https://us.autoartmodels.com/', NULL, 315, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS 2016 B.JOHNSON/S.MUCKE/O.PLA #66', NULL, 'http://localhost:9000/minicollections-media/autoart/81610w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS PLAIN COLOR VERSION (LIGHTNING BLUE)', NULL, 'http://localhost:9000/minicollections-media/autoart/81812w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT LE MANS PLAIN COLOR VERSION (RUBY RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/81811w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'DODGE CHARGER SCAT PACK WIDEBODY (TORRED)', NULL, 'http://localhost:9000/minicollections-media/autoart/71759w.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 911 (991.2) GT3 RS WEISSACH PACKAGE ( WHITE )', NULL, 'http://localhost:9000/minicollections-media/autoart/78176w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'FORD MUSTANG SHELBY GT500 (RAPID RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/73098w.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'TOYOTA 2000GT 1967 (GOLD)', NULL, 'http://localhost:9000/minicollections-media/autoart/79549x.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'KOENIGSEGG ONE : 1 (APPLE RED/CARBON FIBER/SILVER STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/20040x.jpg', 'https://us.autoartmodels.com/', NULL, 35, NULL, 'car', NULL, '1:64'),
(3, 'NISSAN SKYLINE 2000 GT-R (KPGC110) TUNED VERSION (SILVER/ CARBON BONNET) *Online Exclusive*', NULL, 'http://localhost:9000/minicollections-media/autoart/77477w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'LEXUS LS 500h (MORELLO RED METALLIC/BLACK INTERIOR)', NULL, 'http://localhost:9000/minicollections-media/autoart/78869w-.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VULCAN (MADAGASCAR ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/70264w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VULCAN (APPLE TREE GREEN METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/70263x.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT 2017 (TRIPLE YELLOW/BLACK STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/72944w.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT 2017 (FROZEN WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/72941w.jpg', 'https://us.autoartmodels.com/', NULL, 220, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN VULCAN (STRATUS WHITE W/ BLUE STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/70261x.jpg', 'https://us.autoartmodels.com/', NULL, 290, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB11 (APPLE TREE GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/70269w.jpg', 'https://us.autoartmodels.com/', NULL, 240, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 675LT (NAPIER GREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/76049w-.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'FORD GT 2017 (SHADOW BLACK/ORANGE STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/72945w.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN DB11 (Q FROSTED GLASS BLUE )', NULL, 'http://localhost:9000/minicollections-media/autoart/70268a.jpg', 'https://us.autoartmodels.com/', NULL, 250, NULL, 'car', NULL, '1:18'),
(3, 'JAGUAR LIGHTWEIGHT E-TYPE (DARK GREY)', NULL, 'http://localhost:9000/minicollections-media/autoart/73647w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'JAGUAR LIGHTWEIGHT E-TYPE (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/73646w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'JAGUAR LIGHTWEIGHT E-TYPE (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/73649w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA (METALLIC RED/SILVER WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/12234w.jpg', 'https://us.autoartmodels.com/', NULL, 490, NULL, 'car', NULL, '1:12'),
(3, 'PAGANI HUAYRA (METALLIC BLUE/SILVER WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/12232w.jpg', 'https://us.autoartmodels.com/', NULL, 490, NULL, 'car', NULL, '1:12'),
(3, 'MERCEDES-BENZ G500 4X4 2 (ALIENGREEN)', NULL, 'http://localhost:9000/minicollections-media/autoart/76315.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'MERCEDES-BENZ G500 4X4 2 (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/76318.jpg', 'https://us.autoartmodels.com/', NULL, 230, NULL, 'car', NULL, '1:18'),
(3, 'LOTUS 3-ELEVEN (YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/75393.jpg', 'https://us.autoartmodels.com/', NULL, 130, NULL, 'car', NULL, '1:18'),
(3, 'LOTUS 3-ELEVEN (MATT BLACK W/ GLOSS BLACK ACCENTS)', NULL, 'http://localhost:9000/minicollections-media/autoart/75391a.jpg', 'https://us.autoartmodels.com/', NULL, 130, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA (GLOSS BLACK & SILVER STRIPES W/SILVER WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/12233.jpg', 'https://us.autoartmodels.com/', NULL, 490, NULL, 'car', NULL, '1:12'),
(3, 'NISSAN JUKE-R 2.0 (RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/77457.jpg', 'https://us.autoartmodels.com/', NULL, 140, NULL, 'car', NULL, '1:18'),
(3, 'CHEVROLET CORVETTE GRAND SPORT (RED/WHITE STRIPES/BLACK FENDER HASH MARKS)', NULL, 'http://localhost:9000/minicollections-media/autoart/71274.jpg', 'https://us.autoartmodels.com/', NULL, 170, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA (WHITE/CHROME WHEELS)', NULL, 'http://localhost:9000/minicollections-media/autoart/12231.jpg', 'https://us.autoartmodels.com/', NULL, 490, NULL, 'car', NULL, '1:12'),
(3, 'LAMBORGHINI HURACAN LP610 POLICE CAR', NULL, 'http://localhost:9000/minicollections-media/autoart/74609q.jpg', 'https://us.autoartmodels.com/', NULL, 205, NULL, 'car', NULL, '1:18'),
(3, 'PORSCHE 918 SPYDER WEISSACH PACKAGE (BLACK/MARTINI LIVERY)', NULL, 'http://localhost:9000/minicollections-media/autoart/77929.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18'),
(3, 'LOTUS 72E 1973 RONNIE PETERSON #2', NULL, 'http://localhost:9000/minicollections-media/autoart/87329.jpg', 'https://us.autoartmodels.com/', NULL, 190, NULL, 'car', NULL, '1:18'),
(3, 'LOTUS 72E 1973 EMERSON FITTIPALDI #1 (WITH DRIVER FIGURINE IN COCKPIT)', NULL, 'http://localhost:9000/minicollections-media/autoart/87328.jpg', 'https://us.autoartmodels.com/', NULL, 215, NULL, 'car', NULL, '1:18'),
(3, 'NISSAN GT-R LM NISMO 2015 TEST CAR', NULL, 'http://localhost:9000/minicollections-media/autoart/81577.jpg', 'https://us.autoartmodels.com/', NULL, 160, NULL, 'car', NULL, '1:18'),
(3, 'HONDA CB1100R (RD) 1983 - WHITE WITH RED AND BLUE STRIPES', NULL, 'http://localhost:9000/minicollections-media/autoart/6011a.jpg', 'https://us.autoartmodels.com/', NULL, NULL, NULL, 'car', NULL, '1:6'),
(3, 'ASTON MARTIN V12 VANTAGE BATHURST 12HOUR ENDURANCE RACE 2015 JM.Merlin/J.Venter/', NULL, 'http://localhost:9000/minicollections-media/autoart/81507.jpg', 'https://us.autoartmodels.com/', NULL, 150, NULL, 'car', NULL, '1:18'),
(3, 'ASTON MARTIN V12 VANTAGE BATHURST 12HOUR ENDURANCE RACE 2015 A.MACDOWALL/D.O''YO', NULL, 'http://localhost:9000/minicollections-media/autoart/81506.jpg', 'https://us.autoartmodels.com/', NULL, 150, NULL, 'car', NULL, '1:18'),
(3, 'KAWASAKI 900 SUPER FOUR(Z1)?]CANDY GREEN/YELLOW STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/6004.jpg', 'https://us.autoartmodels.com/', NULL, 220, NULL, 'car', NULL, '1:6'),
(3, 'PAGANI HUAYRA (BLACK W/SILVER STRIPES)', NULL, 'http://localhost:9000/minicollections-media/autoart/58209a.jpg', 'https://us.autoartmodels.com/', NULL, 60, NULL, 'car', NULL, '1:43'),
(3, 'PAGANI HUAYRA (BRONZE)', NULL, 'http://localhost:9000/minicollections-media/autoart/58207a.jpg', 'https://us.autoartmodels.com/', NULL, 60, NULL, 'car', NULL, '1:43'),
(3, 'HONDA RA272 F1 GRAND PRIX MEXICO 1965 RICHIE GINTHER #11 (WITH DRIVER FIGURE FIT', NULL, 'http://localhost:9000/minicollections-media/autoart/86599.jpg', 'https://us.autoartmodels.com/', NULL, 365, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI COUNTACH 5000 S (BLACK) (WITH OPENINGS)', NULL, 'http://localhost:9000/minicollections-media/autoart/54532.jpg', 'https://us.autoartmodels.com/', NULL, 165, NULL, 'car', NULL, '1:43'),
(3, 'LAMBORGHINI HURACAN LP610-4 (GRIGIO TITANS/MATT GREY)', NULL, 'http://localhost:9000/minicollections-media/autoart/12099.jpg', 'https://us.autoartmodels.com/', NULL, 390, NULL, 'car', NULL, '1:12'),
(3, '1/18 RED BULL X2014 FAN CAR (HYPER SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/18117.jpg', 'https://us.autoartmodels.com/', NULL, 170, NULL, 'car', NULL, '1:18'),
(3, '1/18 RED BULL X2014 FAN CAR (DARK SILVER METALLIC)', NULL, 'http://localhost:9000/minicollections-media/autoart/18116.jpg', 'https://us.autoartmodels.com/', NULL, 170, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA (METALLIC SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/58206a.jpg', 'https://us.autoartmodels.com/', NULL, 60, NULL, 'car', NULL, '1:43'),
(3, '1/18 RED BULL X2014 FAN CAR (RED BULL COLOR)', NULL, 'http://localhost:9000/minicollections-media/autoart/18118.jpg', 'https://us.autoartmodels.com/', NULL, 170, NULL, 'car', NULL, '1:18'),
(3, 'PEUGEOT 208 T16 PIKES PEAK RACE CAR 2013 PLAIN COLOR VERSION (BLACK)', NULL, 'http://localhost:9000/minicollections-media/autoart/81356.jpg', 'https://us.autoartmodels.com/', NULL, 130, NULL, 'car', NULL, '1:18'),
(3, 'PEUGEOT 208 T16 PIKES PEAK RACE CAR 2013 PLAIN COLOR VERSION (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/81355.jpg', 'https://us.autoartmodels.com/', NULL, 130, NULL, 'car', NULL, '1:18'),
(3, 'LAMBORGHINI COUNTACH 5000S (BLUE)(WITH OPENINGS)', NULL, 'http://localhost:9000/minicollections-media/autoart/54534.jpg', 'https://us.autoartmodels.com/', NULL, 165, NULL, 'car', NULL, '1:43'),
(3, 'BUGATTI EB110 GT (WHITE)', NULL, 'http://localhost:9000/minicollections-media/autoart/70978.jpg', 'https://us.autoartmodels.com/', NULL, 235, NULL, 'car', NULL, '1:18'),
(3, 'BUGATTI EB110 GT (SILVER)', NULL, 'http://localhost:9000/minicollections-media/autoart/70979.jpg', 'https://us.autoartmodels.com/', NULL, 235, NULL, 'car', NULL, '1:18'),
(3, 'KAWASAKI 750RS (Z2) - CANDY BROWN / ORANGE', NULL, 'http://localhost:9000/minicollections-media/autoart/6006a.jpg', 'https://us.autoartmodels.com/', NULL, 205, NULL, 'car', NULL, '1:6'),
(3, 'KAWASAKI 900 SUPER FOUR (Z1) - CANDY BLUE / GOLD STRIPES', NULL, 'http://localhost:9000/minicollections-media/autoart/6003a.jpg', 'https://us.autoartmodels.com/', NULL, 220, NULL, 'car', NULL, '1:6'),
(3, 'KAWASAKI 900 SUPER FOUR (Z1) - BLACK', NULL, 'http://localhost:9000/minicollections-media/autoart/6002a.jpg', 'https://us.autoartmodels.com/', NULL, 205, NULL, 'car', NULL, '1:6'),
(3, 'KAWASAKI 900 SUPER FOUR (Z1) (CANDY BROWN/ORANGE)', NULL, 'http://localhost:9000/minicollections-media/autoart/6001.jpg', 'https://us.autoartmodels.com/', NULL, 205, NULL, 'car', NULL, '1:6'),
(3, 'PORSCHE 911 (991.2) GT2 RS WEISSACH PACKAGE ( RACING YELLOW)', NULL, 'http://localhost:9000/minicollections-media/autoart/78172w-.jpg', 'https://us.autoartmodels.com/', NULL, 265, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA ROADSTER (VERDE FIRENZE)', NULL, 'http://localhost:9000/minicollections-media/autoart/78288-a.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'PAGANI HUAYRA BC (BLUE/CARBON)', NULL, 'http://localhost:9000/minicollections-media/autoart/78277w-.jpg', 'https://us.autoartmodels.com/', NULL, 375, NULL, 'car', NULL, '1:18'),
(3, 'McLAREN 720S (MEMPHIS RED/METALLIC RED)', NULL, 'http://localhost:9000/minicollections-media/autoart/76072w.jpg', 'https://us.autoartmodels.com/', NULL, 275, NULL, 'car', NULL, '1:18');