import type { TextStyle } from "react-native";
import {
  colors,
  neuFontFamily,
  neuFontSize,
  neuFontWeight,
  neuLetterSpacing,
  neuLineHeight,
} from "@minicollections/theme";

/** Semantic text styles — keep in sync with frontend neumorphism CSS. */
export const neuText = {
  nameplateTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs15,
    fontWeight: neuFontWeight.regular,
    letterSpacing: neuLetterSpacing.nameplateTitle,
    lineHeight: neuFontSize.fs15 * neuLineHeight.nameplateTitle,
    color: colors.text,
    textAlign: "left",
  },
  nameplateSubtitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs11,
    fontWeight: neuFontWeight.regular,
    letterSpacing: neuLetterSpacing.nameplateSubtitle,
    lineHeight: neuFontSize.fs11 * neuLineHeight.nameplateSubtitle,
    color: colors.textSecondary,
    textAlign: "left",
  },
  cardRowName: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
    textAlign: "left",
  },
  cardRowMeta: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs12,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
  },
  headerLogo: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs20,
    fontWeight: neuFontWeight.regular,
    lineHeight: neuFontSize.fs20,
  },
  headerBarLabel: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs16,
    fontWeight: neuFontWeight.regular,
    lineHeight: neuFontSize.fs16,
  },
  headerSlotTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs16,
    fontWeight: neuFontWeight.regular,
    lineHeight: neuFontSize.fs16,
    color: colors.text,
    textAlign: "center",
  },
  screenHeaderTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs16,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  screenHeaderSubtitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
  },
  screenHeaderBack: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs20,
    fontWeight: neuFontWeight.regular,
    color: colors.accent,
  },
  modalTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs17,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  button: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs14,
    fontWeight: neuFontWeight.regular,
    letterSpacing: neuLetterSpacing.button,
  },
  buttonLg: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs16,
    fontWeight: neuFontWeight.regular,
    letterSpacing: neuLetterSpacing.button,
  },
  formLabel: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    letterSpacing: 0.3,
    color: colors.textSecondary,
  },
  formInput: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs14,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  formError: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs12,
    fontWeight: neuFontWeight.regular,
    color: colors.danger,
  },
  body: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  bodySecondary: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
  },
  bodyLg: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs15,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  caption: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs11,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
  },
  tag: {
    fontFamily: neuFontFamily.semiBold,
    fontSize: neuFontSize.fs12,
    fontWeight: neuFontWeight.semiBold,
  },
  badge: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs11,
    fontWeight: neuFontWeight.regular,
  },
  panelLabel: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
  },
  panelBody: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    lineHeight: neuFontSize.fs13 * neuLineHeight.panelBody,
    color: colors.text,
  },
  panelValue: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  link: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.accent,
  },
  authTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs22,
    fontWeight: neuFontWeight.regular,
    letterSpacing: neuLetterSpacing.authTitle,
    color: colors.text,
    textTransform: "uppercase",
  },
  authError: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.danger,
  },
  pickerTrigger: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs14,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  pickerModalTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs17,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  pickerOption: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs13,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  filterSection: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs11,
    fontWeight: neuFontWeight.regular,
    color: colors.textSecondary,
    textTransform: "uppercase",
  },
  statTitle: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs14,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  statHeading: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs16,
    fontWeight: neuFontWeight.regular,
    color: colors.text,
  },
  fabAction: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.size28,
    fontWeight: neuFontWeight.regular,
    color: colors.accent,
  },
  placeholderHero: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs36,
    fontWeight: neuFontWeight.regular,
    color: colors.accent,
  },
  tabLabel: {
    fontFamily: neuFontFamily.regular,
    fontSize: neuFontSize.fs12,
    fontWeight: neuFontWeight.regular,
  },
} satisfies Record<string, TextStyle>;
