-- GreenLight brand_objects (brand_id=36). 66 products; image_source: https://www.greenlighttoys.com/
INSERT INTO brand_objects (name_en, name_zh, image_url, image_source, release_price_cny, release_price_usd, release_date, brand_id, category_id, scale_id) VALUES
('IndyCar', 'IndyCar', 'http://localhost:9000/minicollections-media/greenlight/indycar-2.png', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('IndyCar #2', 'IndyCar #2', 'http://localhost:9000/minicollections-media/greenlight/indycar.png', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 12),
('GMP', 'GMP', NULL, 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 12),
('Bespoke Collection', 'Bespoke Collection', 'http://localhost:9000/minicollections-media/greenlight/bespoke-collection.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 8),
('GreenLight 1:43 Scale', 'GreenLight 1:43 Scale', 'http://localhost:9000/minicollections-media/greenlight/greenlight-143-scale.png', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 21),
('Kings of Crunch', 'Kings of Crunch', 'http://localhost:9000/minicollections-media/greenlight/kings-of-crunch-2.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 21),
('Hollywood', 'Hollywood', 'http://localhost:9000/minicollections-media/greenlight/hollywood-3.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 21),
('Jeep Wranglers', '吉普 牧马人', 'http://localhost:9000/minicollections-media/greenlight/jeep-wranglers.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 21),
('GreenLight 1:24 Scale', 'GreenLight 1:24 Scale', 'http://localhost:9000/minicollections-media/greenlight/greenlight-124-scale.png', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15),
('Hitch and Tow Trailers', '拖挂拖车', 'http://localhost:9000/minicollections-media/greenlight/hitch-and-tow-trailers.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 15),
('Tokyo Torque', 'Tokyo Torque', 'http://localhost:9000/minicollections-media/greenlight/tokyo-torque.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15),
('Running on Empty', 'Running on Empty', 'http://localhost:9000/minicollections-media/greenlight/running-on-empty-2.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15),
('Hot Pursuit', 'Hot Pursuit', 'http://localhost:9000/minicollections-media/greenlight/hot-pursuit-2.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15),
('Hollywood #2', 'Hollywood #2', 'http://localhost:9000/minicollections-media/greenlight/hollywood-2.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15),
('GreenLight 1:18 Scale', 'GreenLight 1:18 Scale', 'http://localhost:9000/minicollections-media/greenlight/greenlight-118-scale.png', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 12),
('Vintage Gas Pumps', '复古加油泵', 'http://localhost:9000/minicollections-media/greenlight/vintage-gas-pumps.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 12),
('Highway 61', 'Highway 61', 'http://localhost:9000/minicollections-media/greenlight/highway-61.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 12),
('Artisan Collection', 'Artisan Collection', 'http://localhost:9000/minicollections-media/greenlight/artisan-collection.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 12),
('First Responders', '第一响应者', NULL, 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Fire and Rescue', '消防救援', 'http://localhost:9000/minicollections-media/greenlight/fire-and-rescue.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Hot Hatches', 'Hot Hatches', 'http://localhost:9000/minicollections-media/greenlight/hot-hatches.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('California Lowriders', 'California Lowriders', 'http://localhost:9000/minicollections-media/greenlight/california-lowriders.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Battalion 64', 'Battalion 64', 'http://localhost:9000/minicollections-media/greenlight/battalion-64.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('The Great Outdoors', 'The Great Outdoors', 'http://localhost:9000/minicollections-media/greenlight/the-great-outdoors.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Racing Hitch and Tow', 'Racing 拖挂', 'http://localhost:9000/minicollections-media/greenlight/racing-hitch-and-tow.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Hollywood Hitch and Tow', 'Hollywood 拖挂', 'http://localhost:9000/minicollections-media/greenlight/hollywood-hitch-and-tow.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Mechanic’s Corner', 'Mechanic’s Corner', 'http://localhost:9000/minicollections-media/greenlight/mechanics-corner.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Norman Rockwell', 'Norman Rockwell', 'http://localhost:9000/minicollections-media/greenlight/norman-rockwell.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Garbage Pail Kids', 'Garbage Pail Kids', 'http://localhost:9000/minicollections-media/greenlight/garbage-pail-kids.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Kings of Crunch #2', 'Kings of Crunch #2', 'http://localhost:9000/minicollections-media/greenlight/kings-of-crunch.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('S.D. Trucks', 'S.D. Trucks', 'http://localhost:9000/minicollections-media/greenlight/s-d-trucks.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('H.D. Trucks', 'H.D. Trucks', 'http://localhost:9000/minicollections-media/greenlight/h-d-trucks.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Down on the Farm', 'Down on the Farm', 'http://localhost:9000/minicollections-media/greenlight/down-on-the-farm.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Hitch and Tow', '拖挂', 'http://localhost:9000/minicollections-media/greenlight/hitch-and-tow.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Dually Drivers', 'Dually Drivers', 'http://localhost:9000/minicollections-media/greenlight/dually-drivers.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Route Runners', 'Route Runners', 'http://localhost:9000/minicollections-media/greenlight/route-runners.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Hollywood #3', 'Hollywood #3', 'http://localhost:9000/minicollections-media/greenlight/hollywood.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Running on Empty #2', 'Running on Empty #2', 'http://localhost:9000/minicollections-media/greenlight/running-on-empty.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Hot Pursuit #2', 'Hot Pursuit #2', 'http://localhost:9000/minicollections-media/greenlight/hot-pursuit.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Busted Knuckle Garage', 'Busted Knuckle Garage', 'http://localhost:9000/minicollections-media/greenlight/busted-knuckle-garage.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Detroit Speed Inc.', 'Detroit Speed Inc.', 'http://localhost:9000/minicollections-media/greenlight/detroit-speed-inc.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Vintage Ad Cars', 'Vintage Ad Cars', 'http://localhost:9000/minicollections-media/greenlight/vintage-ad-cars.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Mecum Auction', 'Mecum Auction', 'http://localhost:9000/minicollections-media/greenlight/mecum-auction.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Barrett Jackson', 'Barrett Jackson', 'http://localhost:9000/minicollections-media/greenlight/barrett-jackson.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Blue Collar Collection', '蓝色 Collar Collection', 'http://localhost:9000/minicollections-media/greenlight/blue-collar-collection.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('All-Terrain', 'All-Terrain', 'http://localhost:9000/minicollections-media/greenlight/all-terrain.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Hitched Homes', 'Hitched Homes', 'http://localhost:9000/minicollections-media/greenlight/hitched-homes.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Estate Wagons', 'Estate Wagons', 'http://localhost:9000/minicollections-media/greenlight/estate-wagons.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Club Vee-Dub', 'Club Vee-Dub', 'http://localhost:9000/minicollections-media/greenlight/club-vee-dub.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Black Bandit', 'Black Bandit', 'http://localhost:9000/minicollections-media/greenlight/black-bandit.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Anniversary Collection', 'Anniversary Collection', 'http://localhost:9000/minicollections-media/greenlight/anniversary-collection.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Wheel and Tire Packs', '轮毂轮胎套装', 'http://localhost:9000/minicollections-media/greenlight/wheel-and-tire-packs.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Shop Tool Accessories', '车间工具配件', 'http://localhost:9000/minicollections-media/greenlight/shop-tool-accessories.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('Hobby Exclusives', 'Hobby 限定款', 'http://localhost:9000/minicollections-media/greenlight/hobby-exclusives.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('The Hobby Shop', 'The Hobby Shop', 'http://localhost:9000/minicollections-media/greenlight/the-hobby-shop.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('Four-Post Lifts', '四柱举升机', 'http://localhost:9000/minicollections-media/greenlight/four-post-lifts.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 7, 27),
('La Carrera Panamericana', '泛美拉力赛', 'http://localhost:9000/minicollections-media/greenlight/la-carrera-panamericana.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('GreenLight Muscle', 'GreenLight Muscle', 'http://localhost:9000/minicollections-media/greenlight/greenlight-muscle.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('1:64 Ron Jon Diorama', '1:64 Ron Jon Diorama', 'http://localhost:9000/minicollections-media/greenlight/51330-1-64-Ron-Jon-Diorama-Pkg-FrontHigh-Res-1.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 8, 27),
('1:64 2020 Dallara IndyCar', '1:64 2020 Dallara IndyCar', 'http://localhost:9000/minicollections-media/greenlight/51338-1-64-2020-Dallara-IndyCar-Indiana-Pacers-Exclusive-Pkg-FrontHigh-Res.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('1:64 2021 Ford Mustang Mach 1 with Driver Figure – Gulf Oil', '1:64 2021 福特 Mustang Mach 1 含车手人偶 – 海湾石油', 'http://localhost:9000/minicollections-media/greenlight/51377-2021-Ford-Mustang-Mach-1-Gulf-Oil-deco-high-res.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('30499_2020 Jeep Gladiator copy-01', '30499_2020 吉普 Gladiator copy-01', 'http://localhost:9000/minicollections-media/greenlight/30499_2020-Jeep-Gladiator-copy-01.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('1969 Chevrolet Camaro – Jimmie Johnson copy-01', '1969 雪佛兰 科迈罗 – Jimmie Johnson copy-01', 'http://localhost:9000/minicollections-media/greenlight/30493-1969-Chevrolet-Camaro-Jimmie-Johnson-copy-01.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('1969 Chevrolet Camaro – Jeff Gordon copy-01', '1969 雪佛兰 科迈罗 – Jeff Gordon copy-01', 'http://localhost:9000/minicollections-media/greenlight/30492-1969-Chevrolet-Camaro-Jeff-Gordon-copy-01.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('C-2022 Ford Bronco Sport Badlands – b2b', 'C-2022 福特 Bronco Sport Badlands – b2b', 'http://localhost:9000/minicollections-media/greenlight/68010-C-2022-Ford-Bronco-Sport-Badlands-b2b.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 27),
('1-24 Corvette C8 Speed Forms – Conv – Accelerate Yellow (Front,High Res)', '1-24 科尔维特 C8 Speed Forms – Conv – 加速黄 (Front,High Res)', 'http://localhost:9000/minicollections-media/greenlight/51326-1-24-Corvette-C8-Speed-Forms-Conv-Accelerate-Yellow-FrontHigh-Res.jpg', 'https://www.greenlighttoys.com/', NULL, NULL, NULL, 36, 1, 15);
