export const DRAWER_WIDTH = 720;

export const Z_INDEX = {
  MODAL_BRAND_OBJECT_DETAIL: 1200,
  MODAL_USER_OBJECT_DETAIL: 1200,
  MODAL_EDIT_USER_OBJECT: 1300,
  SELECT_DROPDOWN_IN_EDIT_MODAL: 1400,
};
