-- LCD 1:64 brand_objects (brand_id=2). 95 products with images in static/images/lcd/
INSERT INTO brand_objects (brand_id, name_en, name_zh, image_url, release_price_cny, release_price_usd, release_date, category_en, category_zh, scale) VALUES
(2, '1-64 Land Rover Defender 90 V8 - Crimea Grey color', NULL, '/images/lcd/1-64-land-rover-defender-90-v8-crimea-grey-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Land Rover Defender 90 V8 - Glasmir Green color', NULL, '/images/lcd/1-64-land-rover-defender-90-v8-glasmi-green-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Land Rover Defender 90 V8 - Vintage Blue color', NULL, '/images/lcd/1-64-land-rover-defender-90-v8-vintage-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota SUPRA A80- Chameleon color', NULL, '/images/lcd/1-64-toyota-supra-a80-chameleon-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota SUPRA A80- Green color', NULL, '/images/lcd/1-64-toyota-supra-a80-green-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota SUPRA A80- Blue color', NULL, '/images/lcd/1-64-toyota-supra-a80-blue-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota SUPRA A80- Yellow color', NULL, '/images/lcd/1-64-toyota-supra-a80-yellow-color.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia Coupe -Blue with black carbon', NULL, '/images/lcd/1-64-pagani-utopia-blue-with-black-carbon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia Coupe -White with blue carbon', NULL, '/images/lcd/1-64-pagani-utopia-white-with-blue-carbon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Zonda C12 Coupe-Blue', NULL, '/images/lcd/1-64-pagani-zonda-c12-coupe-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Zonda C12 Coupe-Black', NULL, '/images/lcd/1-64-pagani-zonda-c12-coupe-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Zonda C12 Coupe-Yellow', NULL, '/images/lcd/1-64-pagani-zonda-c12-coupe-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Zonda C12 Coupe-Silver', NULL, '/images/lcd/1-64-pagani-zonda-c12-coupe-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Huayra BC Roadster Diecast model car-Green color', NULL, '/images/lcd/1-64-pagani-huayra-roadster-bc-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Huracan STO-Silver Grey color', NULL, '/images/lcd/1-64-lamborghini-huracan-sto-silver-grey.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Huracan STO-White color', NULL, '/images/lcd/1-64-lamborghini-huracan-sto-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Huracan STO-Green color', NULL, '/images/lcd/1-64-lamborghini-huracan-sto-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Senna GTR McLaren Orange color', NULL, '/images/lcd/1-64-mclaren-senna-gtr-mclaren-orange.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Zonda-HP Diecast model car -Carbon Red color', NULL, '/images/lcd/1-64-pagani-zonda-hp-carbon-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Apple Green color', NULL, '/images/lcd/1-64-lamborghini-revuelto-apple-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Purple', NULL, '/images/lcd/1-64-lamborghini-revuelto-purple.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Blue', NULL, '/images/lcd/1-64-lamborghini-revuelto-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Yellow', NULL, '/images/lcd/1-64-lamborghini-revuelto-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Green', NULL, '/images/lcd/1-64-lamborghini-revuelto-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Orange', NULL, '/images/lcd/1-64-lamborghini-revuelto-orange.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-White', NULL, '/images/lcd/1-64-lamborghini-revuelto-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Murcielago-Green color', NULL, '/images/lcd/1-64-Lamborghini-Murcielago-Green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Murcielago-Red color', NULL, '/images/lcd/1-64-Lamborghini-Murcielago-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Murcielago-Black color', NULL, '/images/lcd/1-64-Lamborghini-Murcielago-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren MCL35-Orange #3', NULL, '/images/lcd/1-64-McLaren-MCL35-Orange-3.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1/64 McLaren MP4-23', NULL, '/images/lcd/1-64-McLaren-MP4-23-Silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Senna GTR Red and white color', NULL, '/images/lcd/1-64-McLaren-Senna-GTR-Red-and-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola-Matte Black carbon with Italian flag', NULL, '/images/lcd/1-64-pagani-imola-matte-black-carbon-with-Italian-flag.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola-Matte Black carbon', NULL, '/images/lcd/1-64-pagani-imola-matte-black-carbon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Matte Grey', NULL, '/images/lcd/1-64-lamborghini-revuelto-matte-grey.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Matte Green', NULL, '/images/lcd/1-64-lamborghini-revuelto-matte-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lamborghini Revuelto-Matte Black', NULL, '/images/lcd/1-64-lamborghini-revuelto-matte-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren M23 Cosworth', NULL, '/images/lcd/1-64-mclaren-m23-cosworth.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT- Chameleon color', NULL, '/images/lcd/1-64-mclaren-600lt-chameleon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT- Ice Blue color', NULL, '/images/lcd/1-64-mclaren-600lt-ice-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT- Green color', NULL, '/images/lcd/1-64-mclaren-600lt-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT-Metallic blue color', NULL, '/images/lcd/1-64-mclaren-600lt-metallic-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT-Orange color', NULL, '/images/lcd/1-64-mclaren-600lt-orange-2.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT-Yellow color', NULL, '/images/lcd/1-64-mclaren-600lt-yellow-2.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren 600LT-White color', NULL, '/images/lcd/1-64-mclaren-600lt-white-2.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia Coupe -Yellow color', NULL, '/images/lcd/1-64-pagani-utopia-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia Coupe -Red color', NULL, '/images/lcd/1-64-pagani-utopia-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia Coupe -Black with white color', NULL, '/images/lcd/1-64-pagani-utopia-black-with-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Light Blue', NULL, '/images/lcd/1-64-mclaren-p1-light-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Orange', NULL, '/images/lcd/1-64-mclaren-p1-orange.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Yellow', NULL, '/images/lcd/1-64-mclaren-p1-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-White', NULL, '/images/lcd/1-64-mclaren-p1-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola Coupe-Chameleon', NULL, '/images/lcd/1-64-pagani-imola-chameleon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola Coupe-Red', NULL, '/images/lcd/1-64-pagani-imola-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola Coupe-Grey', NULL, '/images/lcd/1-64-pagani-imola-grey.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Imola Coupe-Silver', NULL, '/images/lcd/1-64-pagani-imola-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani HuayraR-Green', NULL, '/images/lcd/1-64-pagani-huayra-r-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda Integra Type R (DC5)-White', NULL, '/images/lcd/1-64-honda-integra-type-r-dc5-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda Integra Type R (DC5)-Blue', NULL, '/images/lcd/1-64-honda-integra-type-r-dc5-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda Integra Type R (DC5)-Red', NULL, '/images/lcd/1-64-honda-integra-type-r-dc5-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda Integra Type R (DC5)-Silver', NULL, '/images/lcd/1-64-honda-integra-type-r-dc5-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda Integra Type R (DC5)-Black', NULL, '/images/lcd/1-64-honda-integra-type-r-dc5-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Land Rover Range Rover 2022 -Green and White', NULL, '/images/lcd/1-64-range-rover-2022-green-and-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Land Rover Range Rover 2022 -Black and White', NULL, '/images/lcd/1-64-range-rover-2022-black-and-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia-Carbon Black', NULL, '/images/lcd/1-64-pagani-utopia-carbon-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Purple', NULL, '/images/lcd/1-64-mclaren-p1-purple.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Red', NULL, '/images/lcd/1-64-mclaren-p1-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Blue', NULL, '/images/lcd/1-64-mclaren-p1-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren P1-Black', NULL, '/images/lcd/1-64-mclaren-p1-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani Utopia-White', NULL, '/images/lcd/1-64-pagani-utopia-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Honda MP4/6-White', NULL, '/images/lcd/1-64-mclaren-mp4-6-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Pagani HuayraR-Pearl White', NULL, '/images/lcd/1-64-pagani-huayra-r-pearl-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-Yellow', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-White', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-Black', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota Supra A80-Silver', NULL, '/images/lcd/1-64-toyota-supra-a80-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota Supra A80-Red', NULL, '/images/lcd/1-64-toyota-supra-a80-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota Supra A80-White', NULL, '/images/lcd/1-64-toyota-supra-a80-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Toyota Supra A80-Black', NULL, '/images/lcd/1-64-toyota-supra-a80-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda NSX-NA1 Yellow', NULL, '/images/lcd/1-64-honda-nsx-na1-yellow.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda NSX-NA1 Red', NULL, '/images/lcd/1-64-honda-nsx-na1-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda NSX-NA1 White', NULL, '/images/lcd/1-64-honda-nsx-na1-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda NSX-NA1 Black', NULL, '/images/lcd/1-64-honda-nsx-na1-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-Silver', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-Blue', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Honda CIVIC SiR II(EG6)-Red', NULL, '/images/lcd/1-64-honda-civic-sirii-eg6-red.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lexus LX600-Nori Green', NULL, '/images/lcd/1-64-lexus-lx600-nori-green.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lexus LX600-Grey', NULL, '/images/lcd/1-64-lexus-lx600-grey.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lexus LX600-Silver', NULL, '/images/lcd/1-64-lexus-lx600-silver.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lexus LX600-White', NULL, '/images/lcd/1-64-lexus-lx600-white.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Lexus LX600-Black', NULL, '/images/lcd/1-64-lexus-lx600-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 Land Rover Range Rover 2022 - Black', NULL, '/images/lcd/1-64-range-rover-2022-black.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Speedtail- Black Carbon', NULL, '/images/lcd/1-64-mclaren-speedtail-blackcarbon.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Speedtail- Gold', NULL, '/images/lcd/1-64-mclaren-speedtail-gold.jpg', NULL, NULL, NULL, 'car', NULL, '1:64'),
(2, '1-64 McLaren Speedtail-Blue', NULL, '/images/lcd/1-64-mclaren-speedtail-blue.jpg', NULL, NULL, NULL, 'car', NULL, '1:64');
