INSERT INTO brand_objects (brand_id, name, image_url) VALUES
(1, 'Honda NS-X Prototype Midship Sports 1989  Ayrton Senna w/ Figure', '/images/minigt/2067.JPG'),
(1, 'Honda Civic Type R Ultimate Edition', '/images/minigt/1983.JPG'),
(1, 'Honda Civic TYPE R 2024 Pace Car HRC', '/images/minigt/1858.JPG'),
(1, 'Honda NSX-GT "Type S" GT500 #64 "Modulo NSX-GT"  Modulo Nakajima Racing  2023 SUPER GT Series', '/images/minigt/1733.JPG'),
(1, 'Honda NSX-GT "Type S" GT500 #16 "ARTA MUGEN NSX-GT "  ARTA 2023 SUPER GT Series', '/images/minigt/1732.JPG'),
(1, 'Honda NSX-GT "Type S" GT500 #8 "ARTA MUGEN NSX-GT "  ARTA 2023 SUPER GT Series', '/images/minigt/1731.JPG'),
(1, 'Honda S2000 (AP2) American Honda Collection Hall 2024 Holiday Limited Edition', '/images/minigt/1693.JPG'),
(1, 'Honda NSX-GT "TYPE S" GT500 #16 "Red Bull MOTUL MUGEN NSX-GT "  TEAM Red Bull MUGEN  2022 SUPER GT SERIES', '/images/minigt/1594.JPG'),
(1, 'Honda NSX-GT "Type S" GT500 #16 "Red Bull MOTUL MUGEN NSX-GT"  2022 SUPER GT Series Rd.1 Okayama', '/images/minigt/1562.JPG'),
(1, 'Honda NSX GT3 EVO22 #18 "UPGARAGE NSX GT3" TEAM UPGARAGE 2023 SUPER GT SERIES', '/images/minigt/1436.JPG'),
(1, 'Honda NSX GT3 EVO AlphaTauri  Yuki Tsunoda   2023 Red Bull Formula Nurburgring', '/images/minigt/1427.JPG'),
(1, 'Honda Civic Type R #3 2023 Pace Car Blue', '/images/minigt/1421.JPG'),
(1, 'Honda S2000 （AP2) CR Grand Prix White', '/images/minigt/1391.JPG'),
(1, 'Honda Civic Type R #2 2023 Pace Car White', '/images/minigt/1327.JPG'),
(1, 'Honda Civic TYPE R 2023 Pace Car Red', '/images/minigt/1285.JPG'),
(1, 'Honda Civic Type R Sonic Gray Pearl 2023', '/images/minigt/1231.JPG'),
(1, 'Honda Civic Type R Boost Blue Pearl 2023', '/images/minigt/1194.JPG'),
(1, 'Honda Civic Type R 2023 Honda  Thanks Day Vietnam', '/images/minigt/1172.JPG'),
(1, 'Honda Civic Type R Crystal Black Pearl 2023 W/ Advan GT Wheel', '/images/minigt/1119.JPG'),
(1, 'Honda NSX GT3 EVO22 #18 TEAM UPGARAGE 2022 SUPER GT SERIES', '/images/minigt/562.JPG'),
(1, 'Honda Civic Type R Rallye Red 2023 W/ Advan GT Wheel', '/images/minigt/551.JPG'),
(1, 'Honda Civic Type R Championship White 2023', '/images/minigt/539.JPG'),
(1, 'Honda S2000 (AP2) Mugen Monte Carlo Blue Pearl', '/images/minigt/496.JPG'),
(1, 'Honda NSX GT3 EVO22 #55 ARTA 2022 Super GT Series', '/images/minigt/487.JPG'),
(1, 'Honda S2000 (AP2) Lime Green Metallic', '/images/minigt/396.JPG'),
(1, 'Honda S2000 (AP2) Type S Apex Blue', '/images/minigt/374.JPG'),
(1, 'Honda S2000 (AP2) MUGEN New Formula Red', '/images/minigt/365.JPG'),
(1, 'Honda S2000 (AP2) Type S Grand Prix White', '/images/minigt/342.JPG'),
(1, 'Honda S2000 (AP2) MUGEN  Berlina Black', '/images/minigt/291.JPG'),
(1, 'Honda S2000 (AP2) Laguna Blue Pearl', '/images/minigt/258.JPG'),
(1, 'Honda S2000 Type S New Indy Yellow Pearl', '/images/minigt/256.JPG'),
(1, 'Honda S2000 CR Rio Yellow Pearl', '/images/minigt/255.JPG'),
(1, 'Honda Civic Type R  HKS 2018 Time Attack', '/images/minigt/94.JPG'),
(1, 'Honda Civic Type R (FK8) HKS Black', '/images/minigt/78.JPG'),
(1, 'Honda Civic Type R (FK8) Blitz Type R', '/images/minigt/77.JPG'),
(1, 'Honda Civic Type R (FK8)  2018 Indonesia Motor Show', '/images/minigt/53.JPG'),
(1, 'Honda Civic Type R (FK8)  Championship white w/ Carbon Kit & TE37 Wheel', '/images/minigt/48.JPG'),
(1, 'Honda NSX GT3 #30  2018 24 Hours of Spa', '/images/minigt/45.JPG'),
(1, 'NSX GT3 2019 MINI GT Gift Car', '/images/minigt/41.JPG'),
(1, 'Honda Civic Type R (FK8) ADAC TCR Germany  Safety Car', '/images/minigt/40.JPG'),
(1, 'Honda Civic Type R (FK8) Rallye Red Modulo Edition', '/images/minigt/39.JPG'),
(1, 'Honda NSX GT3 Tokyo Auto Salon 2018', '/images/minigt/36.JPG'),
(1, 'Honda Civic Type R (FK8)  Slate Grey w/ TE37 Wheel', '/images/minigt/32.JPG'),
(1, 'Honda NSX GT3 #84', '/images/minigt/28.JPG'),
(1, 'Honda NSX GT3 Presentation', '/images/minigt/23.JPG'),
(1, 'Honda Civic Type R (FK8)', '/images/minigt/22.JPG'),
(1, 'Honda Civic Type R (FK8)', '/images/minigt/21.JPG'),
(1, 'Honda Civic Type R (FK8) Aegean Blue Modulo Edition', '/images/minigt/18.JPG'),
(1, 'Honda Civic Type R (FK8) Crystal Black', '/images/minigt/17.JPG'),
(1, '1/64 Honda Civic Type R (FK8)  ArtCar Manga - 2018 Paris Autoshow', '/images/minigt/16.JPG'),
(1, 'Honda Civic Type R (FK8) Crystal Black Modulo Edition - RHD', '/images/minigt/15.JPG'),
(1, 'Honda Civic Type R (FK8) Rallye Red', '/images/minigt/13.JPG'),
(1, 'Honda Civic Type R (FK8) Championship White Modulo Edition', '/images/minigt/11.JPG'),
(1, 'Honda Civic Type R (FK8) Phoenix Yellow', '/images/minigt/8.JPG'),
(1, 'Honda Civic Type R (FK8) Aegean Blue Metallic', '/images/minigt/2.JPG'),
(1, 'Honda Civic Type R (FK8) Championship White', '/images/minigt/1.JPG'),
(1, 'Chevrolet Corvette Z06 GT3.R #4 Corvette Racing by Pratt Miller Motorsports 2025 IMSA Daytona 24 Hrs', '/images/minigt/2123.JPG'),
(1, 'Chevrolet Corvette Z06 GT3.R Road America Test car', '/images/minigt/2083.JPG'),
(1, 'Chevrolet Corvette Z06 GT3.R #3 Corvette Racing by Pratt Miller Motorsports 2025 IMSA Daytona 24 Hrs', '/images/minigt/2002.JPG'),
(1, 'Chevrolet Corvette ZR1  Accelerate Yellow', '/images/minigt/1992.JPG'),
(1, 'Chevrolet Corvette Z06 GT3.R #3 Corvette Racing by Pratt Miller Motorsports 2024 IMSA Daytona 24 Hrs', '/images/minigt/1565.JPG'),
(1, 'Corvette Racing C8.R Racing Transporter Set', '/images/minigt/1265.JPG'),
(1, 'Chevrolet Corvette Z06 2023  Arctic White', '/images/minigt/1256.JPG'),
(1, 'Chevrolet Corvette C8.R  Stars & Stripes 2023    USA Exclusive', '/images/minigt/569.JPG'),
(1, 'Chevrolet Corvette Z06 2023 Torch Red', '/images/minigt/482.JPG'),
(1, 'Chevrolet Corvette C8.R #63 2021 Le Mans 24 Hrs GTE PRO 2nd Place', '/images/minigt/381.JPG'),
(1, 'Chevrolet Corvette C8.R #4  2021 IMSA Sebring  12 Hrs', '/images/minigt/298.JPG'),
(1, 'Chevrolet Corvette C8.R #3     Corvette Racing    2021 IMSA Sebring  12 Hrs', '/images/minigt/297.JPG'),
(1, 'Chevrolet Corvette C8.R #4 2020 IMSA 24 Hrs of Daytona', '/images/minigt/238.JPG'),
(1, 'Chevrolet Corvette C8.R #3 2020 IMSA 24 Hrs of Daytona', '/images/minigt/236.JPG'),
(1, 'Chevrolet Corvette Stingray Rapid Blue', '/images/minigt/234.JPG'),
(1, 'Chevrolet Corvette Stingray Sebring Orange Tintcoat', '/images/minigt/211.JPG'),
(1, 'Chevrolet Corvette Stingray Accelerate Yellow Metallic', '/images/minigt/171.JPG'),
(1, 'Chevrolet Corvette Stingray Black w/ Midnight Gray Stripe', '/images/minigt/135.JPG'),
(1, 'Chevrolet Corvette Stingray 2020  Torch Red', '/images/minigt/129.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Suppaiman Okinawa', '/images/minigt/2124.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Suppaiman Okinawa w/Gold Wheel', '/images/minigt/2121.JPG'),
(1, 'Liberty Walk Project FF-R Collection', '/images/minigt/2100.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA   #555 Team MINI GT Liberty Walk 2025 Formula Drift Halloween Special', '/images/minigt/2082.JPG'),
(1, 'Nissan LB-Super Silhouette 180SX   2026 TAS', '/images/minigt/2079.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT RONIN', '/images/minigt/2065.JPG'),
(1, 'LB★WORKS Toyota GR Supra Red', '/images/minigt/2016.JPG'),
(1, 'Lamborghini Countach LB-WORKS Red', '/images/minigt/2015.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Green Chrome 2025 One Night in Brazil', '/images/minigt/2013.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Green Chrome 2025 Salão  DieCast 6', '/images/minigt/2012.JPG'),
(1, 'Lamborghini Countach LB-WORKS Black', '/images/minigt/2007.JPG'),
(1, 'Nissan Silvia (S15) LB-Super Silhouette #555 Team MINI GT Liberty Walk 2025 Formula Drift', '/images/minigt/1991.JPG'),
(1, 'Toyota GR86 LB★Nation   Black / Gold', '/images/minigt/1985.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE   MINI GT Give x Diecast Talk — For Susan G. Komen', '/images/minigt/1976.JPG'),
(1, 'Lamborghini LB-Silhouette WORKS MURCIELAGO GT Evo Yellow', '/images/minigt/1972.JPG'),
(1, 'LB★WORKS Lamborghini Aventador Limited Edition Orange MDX 2025', '/images/minigt/1942.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2  Blue', '/images/minigt/1923.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Red Chrome', '/images/minigt/1919.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA  Chrome', '/images/minigt/1918.JPG'),
(1, 'LB★WORKS Lamborghini Aventador Limited Edition Matte Black', '/images/minigt/1863.JPG'),
(1, 'McLaren 720S LB★Works The Boring Concept', '/images/minigt/1860.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA GARASIDRIFT x LBWK 2025', '/images/minigt/1859.JPG'),
(1, 'LB-WORKS FORD MUSTANG Triple Yellow', '/images/minigt/1856.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA   #555 V2  2024 Formula Drift Japan', '/images/minigt/1849.JPG'),
(1, 'Abarth 595 LB-WORKS x Abas Works  Fighters', '/images/minigt/1847.JPG'),
(1, 'Lamborghini LB-Silhouette WORKS MURCIELAGO GT Evo  Black', '/images/minigt/1846.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette ATHLETE/COLLET', '/images/minigt/1838.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT GRAVITY', '/images/minigt/1832.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA ATHLETE', '/images/minigt/1831.JPG'),
(1, 'LB-WORKS FORD MUSTANG  LB Gold', '/images/minigt/1824.JPG'),
(1, 'Abarth 595 LB-WORKS x Abas Works  Grey', '/images/minigt/1820.JPG'),
(1, 'Mazda RX-7 LB-Super Silhouette 787B', '/images/minigt/1800.JPG'),
(1, 'Abarth 595 LB-WORKS x Abas Works IZTK', '/images/minigt/1782.JPG'),
(1, 'Mazda AZ-1 Liberty Walk LB40 PILOT', '/images/minigt/1778.JPG'),
(1, 'LIBERTY WALK x A BATHING APE Nissan Set', '/images/minigt/1757.JPG'),
(1, 'Nissan GT-R R35 LB★WORKS Type 2, Rear Wing ver 3 LBWK *A BATHING APE CROSSOVER', '/images/minigt/1756.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA LBWK *A BATHING APE CROSSOVER', '/images/minigt/1755.JPG'),
(1, 'Nissan Skyline Kenmeri Liberty Walk  LBWK *A BATHING APE CROSSOVER', '/images/minigt/1754.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE  LBWK *A BATHING APE CROSSOVER', '/images/minigt/1753.JPG'),
(1, 'MAZDA RX-7 LB-Super Silhouette LBWK*A BATHING APE CROSSOVER', '/images/minigt/1752.JPG'),
(1, 'McLaren 720S LB★Works LBWK*A BATHING APE CROSSOVER', '/images/minigt/1751.JPG'),
(1, 'MAZDA RX-7 LB-Super Silhouette IMSA', '/images/minigt/1743.JPG'),
(1, 'Lamborghini Huracan LB★WORKS ver. 2 Mad Mike NIMBUL', '/images/minigt/1737.JPG'),
(1, 'Lamborghini Countach LB-WORKS White 2024 Tokyo Auto Salon', '/images/minigt/1736.JPG'),
(1, 'Mazda RX-7 LB-Super Silhouette Advan', '/images/minigt/1704.JPG'),
(1, 'LB-WORKS x Abas Works ABARTH 595  Red', '/images/minigt/1655.JPG'),
(1, 'Mazda AZ-1 Liberty Walk LB40 White 2024 Tokyo Auto Salon', '/images/minigt/1639.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Black', '/images/minigt/1637.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE  Indonesia Modification Expo 2024', '/images/minigt/1628.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA #555 2023 Formula Drift Japan', '/images/minigt/1624.JPG'),
(1, 'Toyota GR86 LB★Nation   Red', '/images/minigt/1606.JPG'),
(1, 'Toyota GR86 LB★Nation Baby Blue', '/images/minigt/1589.JPG'),
(1, 'McLaren 720S LB★Works Purple', '/images/minigt/1584.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA LBWK 2024 Fausto Racing', '/images/minigt/1566.JPG'),
(1, 'Toyota GR86 LB★Nation LB Gold 2024 All In Tuning Exclusive', '/images/minigt/1559.JPG'),
(1, 'ABARTH 595 LB-WORKS x Abas Works  Pink', '/images/minigt/1552.JPG'),
(1, 'Nissan Skyline Kenmeri Liberty Walk Chrome Blue w/ Baby Pink  "One Night in Beijing"', '/images/minigt/1538.JPG'),
(1, 'Nissan Z LB★NATION WORKS  Gem Red', '/images/minigt/1537.JPG'),
(1, 'Nissan GT-R (R35) LB★WORKS Type 2, Rear Wing ver 3', '/images/minigt/1536.JPG'),
(1, 'Nissan GT-R (R35) LB★WORKS  Type 2, Rear Wing ver 3', '/images/minigt/1535.JPG'),
(1, 'McLaren 720S LB★Works Gem Red', '/images/minigt/1516.JPG'),
(1, 'Nissan Skyline Kenmeri Liberty Walk Chrome Blue  Hobby Expo China 2024', '/images/minigt/1509.JPG'),
(1, 'LB-WORKS x Abas Works ABARTH 595 Gara White', '/images/minigt/1504.JPG'),
(1, 'MAZDA RX-7 LB-Super Silhouette  Liberty Walk Black', '/images/minigt/1488.JPG'),
(1, 'Nissan Z LB★NATION WORKS  LB Gold', '/images/minigt/1486.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA Auto Finesse SEMA 2023', '/images/minigt/1483.JPG'),
(1, 'McLaren 720S LB★Works Black', '/images/minigt/1453.JPG'),
(1, 'MAZDA RX-7 LB-Super Silhouette #41 Numero Reserve', '/images/minigt/1447.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA LBWK KUMA', '/images/minigt/1445.JPG'),
(1, 'Toyota GR86 LB★Nation White', '/images/minigt/1440.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1 LBWK KUMA', '/images/minigt/1378.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA ADVAN', '/images/minigt/1368.JPG'),
(1, 'Nissan Z LB★NATION WORKS Seiran Blue', '/images/minigt/1358.JPG'),
(1, 'Nissan Skyline Kenmeri Liberty Walk White', '/images/minigt/1357.JPG'),
(1, 'Nissan Skyline Kenmeri Liberty Walk LBWK KUMA', '/images/minigt/1307.JPG'),
(1, 'LB-Super Silhouette Nissan SILVIA (S15)“GARUDA”  MINI GT x MIZU Diecast', '/images/minigt/1283.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1 “BARONG”  MINI GT x MIZU Diecast', '/images/minigt/1282.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2  “PRINCESS RORO”  MINI GT x MIZU Diecast', '/images/minigt/1281.JPG'),
(1, 'Nissan SILVIA (S15) LB-Super Silhouette Good-FIX', '/images/minigt/1266.JPG'),
(1, 'LB★WORKS Lamborghini Aventador Limited Edition Yellow', '/images/minigt/1230.JPG'),
(1, 'Lamborghini LB-Silhouette WORKS  Aventador GT EVO Yellow', '/images/minigt/1196.JPG'),
(1, 'Paddock Service Tent Set - LB Racing', '/images/minigt/1169.JPG'),
(1, 'Figurine: Team Liberty Walk', '/images/minigt/1168.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA #23 2022 Goodwood Festival of Speed', '/images/minigt/1167.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2 RHD Gold Series', '/images/minigt/1081.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1 RHD Gold Series', '/images/minigt/1080.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 2, Rear Wing ver 3 RHD Gold Series', '/images/minigt/1079.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 1, Rear Wing ver 1 , RHD Gold Series', '/images/minigt/1078.JPG'),
(1, 'NISSAN LB-Silhouette WORKS GT 35GT-RR Ver.1 LB Racing', '/images/minigt/541.JPG'),
(1, 'Lamborghini  LB-Silhouette WORKS Aventador GT EVO  Matte Black', '/images/minigt/509.JPG'),
(1, 'Lamborghini  LB-Silhouette WORKS Aventador GT EVO Baby Blue', '/images/minigt/498.JPG'),
(1, 'Nissan LB-Silhouette WORKS GT 35GT-RR Ver.2 LB Racing Formula Drift 2022', '/images/minigt/494.JPG'),
(1, 'Nissan LB-Super Silhouette S15 SILVIA Auto Finesse', '/images/minigt/493.JPG'),
(1, 'Toyota GR Supra LB-Works Matte Black', '/images/minigt/475.JPG'),
(1, 'Ford Mustang GT LB-Works Grey', '/images/minigt/473.JPG'),
(1, 'LB-Super Silhouette Nissan S15 SILVIA Presentation', '/images/minigt/470.JPG'),
(1, 'LB Racing Transporter Set', '/images/minigt/467.JPG'),
(1, 'LB-Silhouette WORKS Lamborghini Aventador GT EVO White', '/images/minigt/463.JPG'),
(1, 'LB★WORKS Lamborghini Aventador Limited Edition Matt Silver', '/images/minigt/449.JPG'),
(1, 'LB-Super Silhouette Nissan S15 SILVIA #23 2021 Formula Drift Japan', '/images/minigt/437.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2 Apple Green', '/images/minigt/436.JPG'),
(1, 'LB-WORKS Ford Mustang Grabber Lime', '/images/minigt/427.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2 Passion Pink', '/images/minigt/415.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT Digital Camouflage', '/images/minigt/399.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1 Wonderful Indonesia', '/images/minigt/386.JPG'),
(1, 'LB★WORKS Lamborghini Huracan ver. 2 Red', '/images/minigt/373.JPG'),
(1, 'Isuzu N-Series Vehicle Transporter   LBWK White', '/images/minigt/348.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT Arancio Borealis', '/images/minigt/347.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 2,  Rear Wing ver 3 ,  LB Work Livery 2.0  Red', '/images/minigt/338.JPG'),
(1, 'Mercedes-Benz Actros  w/ 40 Ft Container', '/images/minigt/329.JPG'),
(1, 'LB★WORKS Nissan R35 GT-RR V.2', '/images/minigt/328.JPG'),
(1, 'LB★WORKS Lamborghini Aventador Limited Edition      Infinite Motorsports', '/images/minigt/311.JPG'),
(1, 'LB★WORKS Toyota GR Supra  JPS', '/images/minigt/310.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1  Red/Black', '/images/minigt/306.JPG'),
(1, 'LB★WORKS  BMW M4 IMSA', '/images/minigt/301.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1  LBWK', '/images/minigt/292.JPG'),
(1, 'LB★WORKS Toyota GR Supra CSR2', '/images/minigt/290.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 1, Rear Wing ver 1 Satin Silver', '/images/minigt/287.JPG'),
(1, 'LB★WORKS  BMW M4  Black W/ M Stripe', '/images/minigt/278.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2  LBWK Blue', '/images/minigt/274.JPG'),
(1, 'LB★WORKS Toyota GR Supra  Martini Racing', '/images/minigt/272.JPG'),
(1, 'Isuzu N-Series Vehicle Transporter LBWK Black', '/images/minigt/268.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2 Matt Black LBWK', '/images/minigt/267.JPG'),
(1, 'LB★WORKS Toyota GR Supra Liqui Moly', '/images/minigt/266.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1', '/images/minigt/254.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT  FIGHTERS WORKS', '/images/minigt/240.JPG'),
(1, 'LB★WORKS Toyota GR Supra Black', '/images/minigt/227.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1', '/images/minigt/225.JPG'),
(1, 'LB★WORKS Toyota GR Supra White', '/images/minigt/222.JPG'),
(1, 'LB★WORKS Lamborghini Huracán ver. 1 Black', '/images/minigt/221.JPG'),
(1, 'LB-Silhouette WORKS GT  NISSAN 35GT-RR Ver.1 Yellow', '/images/minigt/205.JPG'),
(1, 'Mercedes-Benz Actros  With 40 Ft Container', '/images/minigt/191.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Type 1, Rear Wing ver 2 ,  Light Blue', '/images/minigt/190.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1 Matte Black', '/images/minigt/189.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.2  White LBWK', '/images/minigt/187.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1  Lava Red', '/images/minigt/178.JPG'),
(1, '5" Display Turntable  Liberty Walk Type B', '/images/minigt/177.JPG'),
(1, '5" Display Turntable  Liberty Walk Type A', '/images/minigt/176.JPG'),
(1, 'LB★WORKS BMW M4 Purple-Green Metallic', '/images/minigt/175.JPG'),
(1, 'LB★WORKS Lamborghini Huracán ver. 1 Light Blue', '/images/minigt/168.JPG'),
(1, 'LB★WORKS  BMW M4  Baby Blue', '/images/minigt/166.JPG'),
(1, 'LB★WORKS Lamborghini Huracán ver. 2 Magic Bronze', '/images/minigt/165.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1  JPS', '/images/minigt/161.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT -  Giallo Auge', '/images/minigt/157.JPG'),
(1, 'LB-Silhouette WORKS GT NISSAN 35GT-RR Ver.1   White', '/images/minigt/143.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT  Magic Green', '/images/minigt/138.JPG'),
(1, 'LB★WORKS BMW M4  White W/ M Stripe', '/images/minigt/137.JPG'),
(1, 'LB★WORKS BMW M4  Red w/ Copper Wheel', '/images/minigt/136.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Magic Green', '/images/minigt/131.JPG'),
(1, 'LB★WORKS Lamborghini Huracán ver. 2  Green', '/images/minigt/127.JPG'),
(1, 'LB★WORKS Lamborghini Huracán ver. 1  White w/ Red Stripe', '/images/minigt/125.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 2 Rear Wing Version 3 JPS', '/images/minigt/122.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35)  LB★WORKS Police', '/images/minigt/119.JPG'),
(1, 'LB WORKS Nissan GT-R (R35) Type 2, Rear Wing Version 3, LB Work Livery 2.0 Blue', '/images/minigt/112.JPG'),
(1, 'LB WORKS Nissan GT-R (R35) Martini Racing', '/images/minigt/109.JPG'),
(1, 'LB★WORKS Lamborghini Huracán GT  White', '/images/minigt/102.JPG'),
(1, 'LB★WORKS Nissan GT-R R35 Type 2 Rear Wing ver 3', '/images/minigt/100.JPG'),
(1, 'LB★WORKS Lamborghini Huracan GT Rosso Mars', '/images/minigt/98.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Magic Pearl', '/images/minigt/82.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Gudang Garam Intersport', '/images/minigt/81.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Black / LB Work Livery 2.0', '/images/minigt/80.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Light Green', '/images/minigt/79.JPG'),
(1, 'LB WORKS Nissan GT-R (R35)  Black w/ Copper Wheel', '/images/minigt/75.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) Metallic Brown', '/images/minigt/70.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) ADVAN', '/images/minigt/69.JPG'),
(1, 'LB★Works Nissan GT-R (R35) Candy Red', '/images/minigt/64.JPG'),
(1, 'LB★Works Nissan GT-R (R35) Pink Pig', '/images/minigt/63.JPG'),
(1, 'LB★WORKS Nissan GT-R (R35) #46 Infinite Motorsport', '/images/minigt/59.JPG'),
(1, 'McLaren MCL38 #81 Oscar Piastri 2024 F1 Monaco GP 2nd Place', '/images/minigt/1999.JPG'),
(1, 'McLaren MCL38 #4 Lando Norris 2024 F1 Monaco GP', '/images/minigt/1998.JPG'),
(1, 'McLaren MCL38 #81 Oscar Piastri 2024 F1 2024 Hungarian GP Winner', '/images/minigt/1982.JPG'),
(1, 'McLaren MCL38 #4 Lando Norris 2024 F1 2024 Hungarian GP 2nd Place', '/images/minigt/1981.JPG'),
(1, 'McLaren MP4/6 #1 Ayrton Senna 1991 Japanese Grand Prix  2nd Place', '/images/minigt/1929.JPG'),
(1, 'McLaren MP4/4 #12 Ayrton Senna 1988 Japanese Grand Prix  Winner', '/images/minigt/1927.JPG'),
(1, 'McLaren MP4/4 #11 Alain Prost 1988 Japanese Grand Prix  2nd Place', '/images/minigt/1922.JPG'),
(1, 'McLaren 720S GT3 Evo Pfaff Motorsports 2024 IMSA Laguna Seca', '/images/minigt/1708.JPG'),
(1, 'McLaren 720S GT3 Evo Pfaff Motorsports 2024 IMSA Daytona 24 Hrs', '/images/minigt/1705.JPG'),
(1, 'McLaren 750S Spider Cirrus Grey', '/images/minigt/1699.JPG'),
(1, 'McLaren 750S  McLaren Orange', '/images/minigt/1677.JPG'),
(1, 'McLaren 750S  Saros Grey', '/images/minigt/1604.JPG'),
(1, 'McLaren F1 GTR #59 1995 Le Mans 24Hr Winner Post-Race Weathered', '/images/minigt/1586.JPG'),
(1, 'McLaren F1 Yquem', '/images/minigt/1512.JPG'),
(1, 'McLaren 750S Spider Belize Blue', '/images/minigt/1506.JPG'),
(1, 'McLaren 750S Spider Mantis Green', '/images/minigt/1487.JPG'),
(1, 'McLaren 750S  Amaranth Red', '/images/minigt/1449.JPG'),
(1, 'McLaren MCL60 #81 Oscar Piastri  2023 F1  2023 Japanese GP 3rd Place', '/images/minigt/1439.JPG'),
(1, 'McLaren MCL60 #4  Lando Norris  2023 F1  2023 Japanese GP 2nd Place', '/images/minigt/1438.JPG'),
(1, 'McLaren F1 Red', '/images/minigt/1389.JPG'),
(1, 'McLaren F1 GTR #33 1996 Le Mans 24Hr', '/images/minigt/1344.JPG'),
(1, 'McLaren F1 GTR 1996 Presentation', '/images/minigt/1271.JPG'),
(1, 'McLaren F1 Cobalt Blue', '/images/minigt/1174.JPG'),
(1, 'McLaren Artura  Ice Silver', '/images/minigt/1083.JPG'),
(1, 'McLaren F1 GTR #59 1995 Le Mans 24Hr Winner', '/images/minigt/544.JPG'),
(1, 'McLaren Artura Vermillion Red LHD', '/images/minigt/542.JPG'),
(1, 'McLaren Artura Flux Green', '/images/minigt/500.JPG'),
(1, 'McLaren Artura Volcano Blue', '/images/minigt/431.JPG'),
(1, 'McLaren Senna  Cerulean Blue', '/images/minigt/296.JPG'),
(1, 'McLaren Senna Antares Blue', '/images/minigt/214.JPG'),
(1, 'McLaren Senna Silver', '/images/minigt/153.JPG'),
(1, 'McLaren Senna  Purple/Yellow', '/images/minigt/111.JPG'),
(1, 'McLaren Senna  Orange / White', '/images/minigt/68.JPG'),
(1, '1/64 McLaren Senna Onyx Black', '/images/minigt/30.JPG'),
(1, 'McLaren Senna White', '/images/minigt/29.JPG'),
(1, 'McLaren Senna Mira Orange', '/images/minigt/19.JPG'),
(1, 'McLaren Senna Victory Grey', '/images/minigt/14.JPG'),
(1, 'Hyundai RN22e (VP1)', '/images/minigt/2128.JPG'),
(1, 'Hyundai Concept N Vision 74 (VP2)', '/images/minigt/2127.JPG'),
(1, 'Hyundai KONA N Phantom Black', '/images/minigt/2126.JPG'),
(1, 'Ford Mustang GT3 #26  DAYTONA® EDITION', '/images/minigt/2101.JPG'),
(1, 'Nissan Z Veilside FFZ400 Orange Chrome', '/images/minigt/2090.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Matsukiyo KOKU 3 Rotor NA-7 w/ Trophy TAS 2025 Best Tuned Car Award', '/images/minigt/2089.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Black', '/images/minigt/2058.JPG'),
(1, 'Porsche 911 (992) GT3 RS Weissach Package Black With Orange 2025 Essen Motor Show Exclusive', '/images/minigt/2017.JPG'),
(1, 'Subaru Impreza WRC99 1999 Rally Australia Winner #5', '/images/minigt/2011.JPG'),
(1, 'Nissan Skyline GT-R (R34) V.Spec Black Pearl W/ TE37 Wheel', '/images/minigt/2009.JPG'),
(1, 'BMW M4 GT3 #91 FIST Team AAI 2025 China GT', '/images/minigt/1977.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Chrome Blue One Night in Malaysia 2025', '/images/minigt/1843.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Chrome Blue Malaysia Diecast Expo 2025', '/images/minigt/1842.JPG'),
(1, 'VeilSide "One Night in China 2025"  Chrome Set', '/images/minigt/1829.JPG'),
(1, 'Veilside Hobby Expo China 2025 Chrome Set', '/images/minigt/1826.JPG'),
(1, 'Top Secret TAS 2025 Gold Chrome Set', '/images/minigt/1825.JPG'),
(1, 'BMW M3 #44   JPS Team BMW  1987 Bathurst 1000 Class 2 Winner', '/images/minigt/1823.JPG'),
(1, 'Toyota GR Supra KUHL 2021 D1GP EVANGELION RACING', '/images/minigt/1819.JPG'),
(1, 'Hyundai N Vision 74', '/images/minigt/1750.JPG'),
(1, 'Hyundai RN22e', '/images/minigt/1749.JPG'),
(1, 'Toyota GR86 Larry Chen’s HKS Turbocharged GR86 2024 LADC@Petersen Automotive Museum Exclusive', '/images/minigt/1748.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione  Martini Racing    Diecast Con Madrid 2025', '/images/minigt/1740.JPG'),
(1, 'Nissan Skyline GT-R (R32) Gunmetal  W/ Matsuda Figure   Tsugio Matsuda Collection No.3  TAS 2025 Exclusive', '/images/minigt/1692.JPG'),
(1, 'Mazda RX-7 RE-Amemiya 20B NA 3ROTOR-7  w/  Ama-san Figure  TAS 2025  Limited Edition RE-Amemiya Exclusive', '/images/minigt/1691.JPG'),
(1, 'Nissan GT-R NISMO GT3  White  2024 NISMO Festival Exclusive', '/images/minigt/1679.JPG'),
(1, 'Nissan GT-R NISMO GT3 #11 "GAINER TANAX GT-R" GAINER 2023 SUPER GT SERIES', '/images/minigt/1613.JPG'),
(1, 'Nissan GT-R NISMO GT3 #10 "PONOS GAINER GT-R" 2023 SUPER GT SERIES', '/images/minigt/1611.JPG'),
(1, 'Nissan GT-R NISMO GT3 #56 " REALIZE NISSAN MECHANIC CHALLENGE GT-R" 2023 SUPER GT SERIES', '/images/minigt/1610.JPG'),
(1, 'Nissan Z GT500 #24 "REALIZE CORPORTATION ADVAN Z" KONDO RACING   2023 SUPER GT SERIES', '/images/minigt/1596.JPG'),
(1, 'Nissan Z GT500 #1 MARELLI IMPUL Z TEAM IMPUL 2023 SUPER GT SERIES', '/images/minigt/1595.JPG'),
(1, 'Porsche Taycan Turbo S  Porsche x Shell', '/images/minigt/1574.JPG'),
(1, 'Land Rover Defender 110  Shell Oil', '/images/minigt/1573.JPG'),
(1, 'Nissan Silvia (S15) D-MAX  #70  D-MAX Racing  2023 D1 Grand Prix', '/images/minigt/1563.JPG'),
(1, 'Red Bull RB16B #33 Max Verstappen 2021 US Grand Prix Winner', '/images/minigt/1561.JPG'),
(1, 'Land Rover Defender 110 Red Bull LUKA 2024 Red Bull Showrun Taichung', '/images/minigt/1560.JPG'),
(1, 'Land Rover Defender 110  1989 Camel Trophy Amazon Team Turkey  Turkey Exclusive', '/images/minigt/1554.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Chrome Blue MINI GT GIVE 2023 CHINA', '/images/minigt/1539.JPG'),
(1, 'Nissan Silvia (S15)  Top Secret Matte Blue w/ Gold Accent   2024 "One Night in Malaysia" Exclusive', '/images/minigt/1470.JPG'),
(1, 'Nissan Silvia (S15)  Top Secret Matte Blue w/ Red Accent   2024 Malaysia Diecast Expo Exclusive', '/images/minigt/1469.JPG'),
(1, 'Nissan Skyline GT-R (R34) Top Secret  Top Secret Gold', '/images/minigt/1444.JPG'),
(1, 'Lamborghini Urus  "UNLOCK ANY ROAD HONG KONG"    HK Exclusive', '/images/minigt/1443.JPG'),
(1, 'BMW M4 GT3 #7 "Studie BMW M4" BMW M Team Studie x CRS 2023 SUPER GT SERIES', '/images/minigt/1435.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #88 "JLOC Lamborghini GT3"  JLOC  2023 SUPER GT SERIES', '/images/minigt/1434.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #87 "Bamboo Airways Lamborghini GT3"  JLOC  2023 SUPER GT SERIES', '/images/minigt/1433.JPG'),
(1, 'Nissan Z GT500 #23 "MOTUL AUTECH Z" NISMO 2023 SUPER GT SERIES', '/images/minigt/1415.JPG'),
(1, 'Nissan Z GT500 #230  2021 NISMO Presentation', '/images/minigt/1414.JPG'),
(1, 'Nissan GT-R NISMO GT3 #360 "RUNUP RIVAUX GT-R" TOMEI SPORTS 2023 SUPER GT SERIES', '/images/minigt/1413.JPG'),
(1, 'Nissan Skyline GT-R Top Secret  VR32 Gold Chrome w/ Carbon Fiber hood  TAS 2024', '/images/minigt/1331.JPG'),
(1, 'Nissan GT-R Nismo GT500  #12 Team Impul  2021 SUPER GT SERIES', '/images/minigt/1192.JPG'),
(1, 'Nissan GT-R Nismo GT500  #3 NDDP Racing with B-Max  2021 SUPER GT SERIES', '/images/minigt/1191.JPG'),
(1, 'Nissan Z Performance 2023 SUPER GT Safety Car 2022 SUPER GT SERIES', '/images/minigt/1190.JPG'),
(1, 'Lamborghini Sián FKP 37 Matte Viola SE30', '/images/minigt/1138.JPG'),
(1, 'BMW M3 #3 JPS Team BMW 1987 ATCC Championship Winner', '/images/minigt/1137.JPG'),
(1, 'Nissan GT-R Nismo GT500 #23 “MOTUL AUTECH GT-R"  NISMO ​2021 SUPER GT SERIES', '/images/minigt/1136.JPG'),
(1, 'Nissan GT-R Nismo GT500 2021 Prototype #230 SUPER GT SERIES', '/images/minigt/1135.JPG'),
(1, 'Lamborghini Huracán GT3 EVO #88 “Weibo Primez LAMBORGHINI GT3” JLOC  2022 SUPER GT SERIES', '/images/minigt/1071.JPG'),
(1, 'Lamborghini Huracán GT3 EVO #87 “Bamboo Airways LAMBORGHINI GT3” JLOC 2022 SUPER GT SERIES', '/images/minigt/1070.JPG'),
(1, 'LB-Silhouette WORKS Lamborghini Aventador GT EVO  Matte Black w/Gold Accent', '/images/minigt/584.JPG'),
(1, 'Acura NSX GT3 EVO22 Chiaki Edition', '/images/minigt/583.JPG'),
(1, 'Nissan GT-R NISMO GT3 #10 TANAX GAINER 2022 Super GT Series  / Super GT Blister Packaging', '/images/minigt/561.JPG'),
(1, 'Land Rover Defender 110  Mobile Brigade Corps (KORPS BRIMOB)', '/images/minigt/534.JPG'),
(1, 'Lamborghini Aventador SVJ  Baby Pink MINI GT give 2022 HK Edition', '/images/minigt/530.JPG'),
(1, 'LB-Silhouette WORKS Lamborghini Aventador GT EVO  Matte Black w/Red Accent', '/images/minigt/518.JPG'),
(1, 'Nissan GT-R NISMO GT3  #56 KONDO RACING  2022 Super GT Series', '/images/minigt/488.JPG'),
(1, 'BMW M4 GT3 #7 BMW Team Studie x CSL 2022 Super GT Series', '/images/minigt/486.JPG'),
(1, 'Nissan Skyline GT-R Top Secret VR32', '/images/minigt/471.JPG'),
(1, 'Nissan Skyline GT-R (R34)V-Spec ll MINI GT Digital Camouflage Yellow', '/images/minigt/447.JPG'),
(1, 'Top Secret Nissan Skyline GT-R VR32 Top Secret Gold', '/images/minigt/438.JPG'),
(1, 'Lamborghini Aventador SVJ  Baby Blue MINI GT give 2022 China Edition', '/images/minigt/426.JPG'),
(1, 'Porsche Taycan Turbo S NaRaYa', '/images/minigt/404.JPG'),
(1, 'Nissan Skyline GT-R (R34) V-Spec II MINI GT Digital Camouflage Grey 2022 Hong Kong Toycar Salon Edit', '/images/minigt/397.JPG'),
(1, 'Nissan Silvia(S15) Rocket Bunny Green 2023 Shizuoka Hobby Show Exclusive', '/images/minigt/395.JPG'),
(1, 'Western Star 49X w/ 40 Ft Container', '/images/minigt/388.JPG'),
(1, 'Nissan GT-R NISMO GT3 2018 PRESENTATION Matte Black', '/images/minigt/387.JPG'),
(1, 'BMW M3 E30 Gulf', '/images/minigt/377.JPG'),
(1, 'Ford GT Mk II     2019 Pebble Beach Concours d''Elegance', '/images/minigt/350.JPG'),
(1, 'HKS Toyota GR Supra No.77 FAT FIVE RACING  2020 D1 Grand Prix', '/images/minigt/349.JPG'),
(1, 'Land Rover Defender 90 Pickup - 2022 Chinese New Year Edition', '/images/minigt/330.JPG'),
(1, 'Nissan Skyline GT-R (R32) Gr. A #21 MINI GT give 2021 HK Edition', '/images/minigt/327.JPG'),
(1, 'BMW M3 #16 Shell  1989 Italian Supertouring Championship', '/images/minigt/326.JPG'),
(1, 'Bentley Flying Spur "Reindeer Eight"', '/images/minigt/320.JPG'),
(1, 'Ford Mustang Shelby GT500 Grabber Lime', '/images/minigt/314.JPG'),
(1, 'Land Rover Defender 110 Malaysian Army', '/images/minigt/302.JPG'),
(1, 'Mazda Miata MX-5 (NA) Tuned Version Classic White', '/images/minigt/295.JPG'),
(1, 'Pandem Toyota GR Supra V1.0   Orange', '/images/minigt/288.JPG'),
(1, 'Land Rover Defender 110 Camel Trophy Support Vehicle', '/images/minigt/286.JPG'),
(1, 'Ford GT GTLM Gulf', '/images/minigt/285.JPG'),
(1, 'Land Rover Defender 110 2021 Hong Kong Toycar Salon Edition', '/images/minigt/263.JPG'),
(1, 'Land Rover Defender 110    Badan Intelijen Negara Indonesia', '/images/minigt/262.JPG'),
(1, 'Nissan GT-R Nismo GT3 EVA 01 Kakusei Edition  - Nismo Festival 2019', '/images/minigt/261.JPG'),
(1, 'Mercedes-Benz Actros w/ Car Carrier trailer', '/images/minigt/260.JPG'),
(1, 'Mercedes-Benz Actros w/ 40 Ft Container   "Gulf"', '/images/minigt/259.JPG'),
(1, 'Bentley Continental GT3 #6  2018 Blancpain GT Series Asia', '/images/minigt/251.JPG'),
(1, 'BMW M3 E30 #42 1991 Deutsche Tourenwagen Meisterschaft', '/images/minigt/250.JPG'),
(1, 'BMW M3 (E30) #1 1992 Guia Race of Macau Winner', '/images/minigt/249.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #10 "Berlin"  1992 Guia Race of Macau', '/images/minigt/244.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #9', '/images/minigt/243.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #11 "Berlin"  1992 Guia Race of Macau', '/images/minigt/242.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #8', '/images/minigt/241.JPG'),
(1, 'Audi RS 6 Avant Silver Digital Camouflage', '/images/minigt/233.JPG'),
(1, 'Audi RS 6 Avant  Silver Digital Camouflage w/ Roof Box', '/images/minigt/232.JPG'),
(1, 'Pandem Toyota GR Supra V1.0  Team TOYO TIRES DRIFT  2019 D1 Grand Prix', '/images/minigt/218.JPG'),
(1, 'Land Rover Defender 110 British Red Cross Search & Rescue', '/images/minigt/217.JPG'),
(1, 'Land Rover Defender 110  Military Camouflage', '/images/minigt/216.JPG'),
(1, 'Land Rover Defender 110 Korlantas Polri – Indonesian Traffic Police', '/images/minigt/215.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #6', '/images/minigt/207.JPG'),
(1, 'Land Rover Defender 110 Gulf', '/images/minigt/206.JPG'),
(1, 'Porsche 911 (991) GT2 RS  Guards Red', '/images/minigt/204.JPG'),
(1, 'EVA RT Test Type-02 X Works GT-R', '/images/minigt/203.JPG'),
(1, 'Mercedes-Benz Actros Container Lorry  SF Express China Edition', '/images/minigt/202.JPG'),
(1, 'Pandem Toyota GR Supra V1.0   Silver', '/images/minigt/196.JPG'),
(1, 'Eva RT Test Type-01 X Works GT-R #33', '/images/minigt/124.JPG'),
(1, 'Pandem Nissan GT-R (R35)  Duck Tail   ROCAF Malataw Fighter', '/images/minigt/118.JPG'),
(1, 'Pandem Nissan GT-R (R35)  GT Wing   ROCAF Malataw Fighter', '/images/minigt/117.JPG'),
(1, 'Pandem Toyota GR Supra V1.0  White', '/images/minigt/116.JPG'),
(1, 'Mercedes-Benz Actros w/ 40 Ft Container   Black', '/images/minigt/113.JPG'),
(1, 'Pandem Nissan GT-R (R35) Metallic Blue', '/images/minigt/86.JPG'),
(1, 'BMW M3 (E30) #6 1991 Guia Race of Macau Winner', '/images/minigt/84.JPG'),
(1, 'Pagani Huayra Roadster White', '/images/minigt/83.JPG'),
(1, 'Pagani Huayra Roadster Black', '/images/minigt/441.JPG'),
(1, 'Pagani Zonda HP Barchetta Rosso Dubai', '/images/minigt/433.JPG'),
(1, 'Pagani Zonda F Blu Argentina', '/images/minigt/408.JPG'),
(1, 'Pagani Zonda F Rosso Dubai', '/images/minigt/380.JPG'),
(1, 'Pagani Zonda HP Barchetta Blue Tricolore', '/images/minigt/368.JPG'),
(1, 'Pagani Zonda F Silver', '/images/minigt/283.JPG'),
(1, 'Pagani Huayra Roadster Arancio Saint Tropez', '/images/minigt/65.JPG'),
(1, 'Pagani Huayra Roadster  Rosso Monza', '/images/minigt/43.JPG'),
(1, 'Pagani Huayra Roadster Blue Francia', '/images/minigt/33.JPG'),
(1, 'Toyota Vellfire 40 KUHL White', '/images/minigt/2081.JPG'),
(1, 'Toyota Alphard 40 KUHL Black', '/images/minigt/2080.JPG'),
(1, 'Toyota Supra VeilSide Combat V-II Black', '/images/minigt/2061.JPG'),
(1, 'Toyota Supra VeilSide Combat V-I White', '/images/minigt/2010.JPG'),
(1, 'Toyota Supra VeilSide Combat V-I Red', '/images/minigt/1978.JPG'),
(1, 'Toyota Supra (A80) Top Secret GT-300 Top Secret Red Chrome', '/images/minigt/1941.JPG'),
(1, 'Toyota Supra (A80) Top Secret GT-300 Top Secret Purple', '/images/minigt/1852.JPG'),
(1, 'Toyota GR86 HKS TYPE R 2022 Tokyo Auto Salon', '/images/minigt/1768.JPG'),
(1, 'Toyota GR86 Larry Chen''s HKS Turbocharged GR86', '/images/minigt/1719.JPG'),
(1, 'Toyota Supra VeilSide Combat V-II Combat Grey', '/images/minigt/1703.JPG'),
(1, 'Toyota Supra (A80) Top Secret GT-300 Top Secret Gold', '/images/minigt/1653.JPG'),
(1, 'Toyota GR86 HKS TYPE R ADVAN 2022 Tokyo Auto Salon', '/images/minigt/1642.JPG'),
(1, 'Pandem Toyota GR Supra V1.0 Pearl White', '/images/minigt/419.JPG'),
(1, 'HKS Toyota GR Supra (A90)   Downshift Blue', '/images/minigt/366.JPG'),
(1, 'Pandem Toyota GR Supra V1.0 #770 Team Cusco Racing 2021 Formula Drift Japan', '/images/minigt/362.JPG'),
(1, 'HKS Toyota GR Supra (A90)   2020 Tokyo Auto Salon', '/images/minigt/343.JPG'),
(1, 'HKS Toyota GR Supra Renaissance Red', '/images/minigt/247.JPG'),
(1, 'Toyota TRD 3000GT Super White', '/images/minigt/245.JPG'),
(1, 'Pandem Toyota GR Supra V1.0  Matte Grey', '/images/minigt/229.JPG'),
(1, 'Toyota Supra (JZA80) Dark Green Pearl Metallic', '/images/minigt/213.JPG'),
(1, 'HKS Toyota GR Supra  Nocturnal', '/images/minigt/210.JPG'),
(1, 'Pandem Toyota GR Supra V1.0  Black', '/images/minigt/198.JPG'),
(1, 'HKS Toyota GR Supra 2019 SEMA Presentation', '/images/minigt/193.JPG'),
(1, 'Toyota Supra (JZA80)  Blue Pearl Metallic', '/images/minigt/192.JPG'),
(1, 'Toyota TRD 3000GT Renaissance Red', '/images/minigt/184.JPG'),
(1, 'Pandem Toyota GR Supra V1.0  Advan SEMA 2019', '/images/minigt/183.JPG'),
(1, 'Toyota TRD 3000GT Alpine Silver Metallic', '/images/minigt/181.JPG'),
(1, 'Pandem Toyota GR Supra V1.0 White', '/images/minigt/162.JPG'),
(1, 'Pandem Toyota GR Supra V1.0   Silver', '/images/minigt/155.JPG'),
(1, 'Toyota Supra (JZA80) Black', '/images/minigt/108.JPG'),
(1, 'Toyota Supra (JZA80) Renaissance Red', '/images/minigt/38.JPG'),
(1, 'Toyota Supra (JZA80) Super White', '/images/minigt/34.JPG'),
(1, 'BMW Z8 "The World Is Not Enough"', '/images/minigt/2069.JPG'),
(1, 'BMW M4 M-Performance Daytona Violet', '/images/minigt/2060.JPG'),
(1, 'BMW i7 xDrive60 Tanzanite Blue Metallic', '/images/minigt/2020.JPG'),
(1, 'BMW Z8 Alpina Alpine Blue', '/images/minigt/2008.JPG'),
(1, 'BMW M3 M Performance Touring Sao Paulo Yellow', '/images/minigt/1997.JPG'),
(1, 'BMW M5 Touring Brooklyn Grey Metallic', '/images/minigt/1996.JPG'),
(1, 'BMW M5 Alpine White', '/images/minigt/1990.JPG'),
(1, 'BMW M3 Competition Touring Portimao Blue Metallic', '/images/minigt/1970.JPG'),
(1, 'BMW M5 Isle of Man Green Metallic', '/images/minigt/1862.JPG'),
(1, 'BMW Z8 Silver', '/images/minigt/1802.JPG'),
(1, 'BMW i7 xDrive60 Alpine White / Black Sapphire', '/images/minigt/1735.JPG'),
(1, 'BMW 750IL Sorrento Blue Metallic', '/images/minigt/1734.JPG'),
(1, 'BMW M3 M Performance Touring Mint Green', '/images/minigt/1694.JPG'),
(1, 'BMW M4 Competition (G82) Portimao Blue', '/images/minigt/1680.JPG'),
(1, 'BMW i7 xDrive60 Mineral White', '/images/minigt/1676.JPG'),
(1, 'BMW i7 xDrive60 Aventurin', '/images/minigt/1638.JPG'),
(1, 'BMW M3 M Performance Touring Daytona Violet', '/images/minigt/1632.JPG'),
(1, 'BMW 750IL  "Tomorrow Never Dies"', '/images/minigt/1622.JPG'),
(1, 'BMW 3.0 CSL White', '/images/minigt/1585.JPG'),
(1, 'BMW M3 Competition Touring  Brooklyn Grey', '/images/minigt/1567.JPG'),
(1, 'BMW i7 xDrive60 Dravit Grey', '/images/minigt/1513.JPG'),
(1, 'BMW M4 Competition (G82) Sakhir Orange', '/images/minigt/1505.JPG'),
(1, 'BMW i7 xDrive60 Black Sapphire', '/images/minigt/1497.JPG'),
(1, 'BMW 750IL Aspen Silver Metallic', '/images/minigt/1476.JPG'),
(1, 'BMW M3 M Performance Touring Alpine White', '/images/minigt/1450.JPG'),
(1, 'BMW M3 Competition Touring Isle of Man Green Metallic', '/images/minigt/1430.JPG'),
(1, 'BMW M4 CSL  Black Sapphire', '/images/minigt/1347.JPG'),
(1, 'BMW M3 Competition Touring  Toronto Red Metallic', '/images/minigt/1309.JPG'),
(1, 'BMW Alpina B7 xDrive  Aventurin', '/images/minigt/1304.JPG'),
(1, 'BMW M Hybrid V8  #25 BMW M Team RLL   2023 IMSA Sebring 12 Hrs 2nd Place', '/images/minigt/1302.JPG'),
(1, 'BMW M4 CSL Alpine White', '/images/minigt/1270.JPG'),
(1, 'BMW M Hybrid V8 GTP #24  2023 IMSA Daytona 24 Hrs', '/images/minigt/1240.JPG'),
(1, 'BMW M4 GT3 #97 Turner Motorsport  IMSA 2023  Laguna Seca GTD 2nd Place', '/images/minigt/1207.JPG'),
(1, 'BMW M4 CSL Frozen Brooklyn Grey Metallic', '/images/minigt/1199.JPG'),
(1, 'BMW M4 GT3 #1 ​ IMSA 2023 Sebring 12 Hrs GTD Winner', '/images/minigt/1198.JPG'),
(1, 'BMW Alpina B7 xDrive  Dravit Grey Metallic', '/images/minigt/1166.JPG'),
(1, 'BMW M4 GT3 #31 Schubert Motorsport 2022 DTM Champion', '/images/minigt/564.JPG'),
(1, 'BMW M4 M-Performance (G82) Fire Orange', '/images/minigt/536.JPG'),
(1, 'BMW 750Li xDrive Bernina Grey Amber Effect', '/images/minigt/528.JPG'),
(1, 'BMW Alpina B7 xDrive Alpina Green Metallic', '/images/minigt/502.JPG'),
(1, 'BMW Alpina B7 xDrive Alpina Blue Metallic', '/images/minigt/474.JPG'),
(1, 'BMW M4 Competition (G82) San Paulo Yellow', '/images/minigt/464.JPG'),
(1, 'BMW M4 GT3 #96 2022 IMSA Daytona 24 Hrs', '/images/minigt/458.JPG'),
(1, 'BMW M4 GT3 #1 2022 12H Mugello Winner', '/images/minigt/443.JPG'),
(1, 'BMW 750Li xDrive Black Sapphire', '/images/minigt/432.JPG'),
(1, 'BMW M4 GT3 #25 BMW Team RLL 2022 IMSA Daytona 24 Hrs', '/images/minigt/416.JPG'),
(1, 'BMW M4 GT3 #24 2022 IMSA Daytona 24 Hrs', '/images/minigt/394.JPG'),
(1, 'BMW M4 GT3 2021 Presentation', '/images/minigt/340.JPG'),
(1, 'BMW M4 M-Performance (G82) Alpine White', '/images/minigt/339.JPG'),
(1, 'BMW M3  AC Schnitzer S3 Sport  Black', '/images/minigt/195.JPG'),
(1, 'BMW M3 (E30) ALPINA B6 3.5S Alpina Blue', '/images/minigt/185.JPG'),
(1, 'BMW M4 (F82) Austin Yellow Metallic', '/images/minigt/169.JPG'),
(1, 'BMW M4 (F82) Sakhir Orange', '/images/minigt/133.JPG'),
(1, 'BMW M4 (F82)  Yas Marina Blue Metallic', '/images/minigt/104.JPG'),
(1, 'BMW M3 Henna Red', '/images/minigt/55.JPG'),
(1, 'BMW M3 (E30) Alpine White', '/images/minigt/47.JPG'),
(1, 'Acura ARX-06 GTP #10  Wayne Taylor Racing with Andretti  2024 IMSA Daytona 24 Hrs', '/images/minigt/1833.JPG'),
(1, 'Acura ARX-06 GTP #40 Wayne Taylor Racing with Andretti 2024 IMSA Sebring 12Hrs Winner', '/images/minigt/1722.JPG'),
(1, 'Acura ARX-06 GTP #10  No. 10 Konica Minolta Acura ARX-06 2023 IMSA Daytona 24 Hrs', '/images/minigt/1272.JPG'),
(1, 'Acura ARX-06 GTP #60  2023 IMSA Daytona 24 Hrs  Winner', '/images/minigt/1238.JPG'),
(1, 'Acura NSX GT3 EVO22 #93 2023 IMSA Daytona 24 Hrs', '/images/minigt/1165.JPG'),
(1, 'Acura NSX GT3 EVO #44  2021 IMSA Daytona 24 Hrs', '/images/minigt/280.JPG'),
(1, 'Acura NSX GT3 EVO #57  2020 IMSA 24 Hrs of Daytona', '/images/minigt/228.JPG'),
(1, 'Acura NSX GT3 EVO #86  2019 IMSA Watkins Glen Class Winner', '/images/minigt/120.JPG'),
(1, 'Acura NSX GT3  Gulf Racing', '/images/minigt/72.JPG'),
(1, 'Acura NSX GT3 NY Autoshow 2016', '/images/minigt/71.JPG'),
(1, 'Acura NSX GT3 #93  Statue of Liberty" 2017 IMSA Watkins Glen', '/images/minigt/56.JPG'),
(1, 'Acura NSX GT3 #86 "Uncle Sam" 2017 IMSA Watkins Glen', '/images/minigt/46.JPG'),
(1, 'Acura NSX GT3  Los Angeles Auto Show 2017', '/images/minigt/24.JPG'),
(1, 'Porsche 911 (992.1) Rubystone Red Set', '/images/minigt/2129.JPG'),
(1, 'Porsche 911(992) GT3 RS Weissach RingTaxi.com', '/images/minigt/2066.JPG'),
(1, 'Porsche 911 GT3 R #77 AO Racing 2025 IMSA  Petit Le Mans', '/images/minigt/2057.JPG'),
(1, 'Porsche 911 Carrera RS 2.7 Tangerine with Black Livery', '/images/minigt/1975.JPG'),
(1, 'Porsche 911 Dakar #718  / Volkswagen ID. Buzz  Porsche Centrum Gelderland Roughroads Set', '/images/minigt/1925.JPG'),
(1, 'Porsche 911 Dakar "Uncle Rally"', '/images/minigt/1853.JPG'),
(1, 'Porsche 911 GT3 R #77 AO Racing 2024 IMSA Road America', '/images/minigt/1845.JPG'),
(1, 'Porsche 911 Dakar "Uncle Rally"', '/images/minigt/1844.JPG'),
(1, 'Porsche 911 (992) GT3 RS Weissach Package Guards Red', '/images/minigt/1834.JPG'),
(1, 'Porsche 911 Dakar  Rally 1974', '/images/minigt/1830.JPG'),
(1, 'Porsche 911 Dakar Black', '/images/minigt/1706.JPG'),
(1, 'Porsche 911 Dakar Ice Grey Metallic "Rally 1978"', '/images/minigt/1656.JPG'),
(1, 'Porsche 911 Dakar Ice Gray Metallic', '/images/minigt/1630.JPG'),
(1, 'Porsche 911 GT3 R #77 AO Racing 2024 IMSA Daytona 24 Hrs GTD Pro 2nd Place', '/images/minigt/1627.JPG'),
(1, 'Porsche 911 GT3 R #80 AO Racing 2023 IMSA VIRginia Roxy', '/images/minigt/1588.JPG'),
(1, 'Porsche 911 (992) GT3 RS Weissach Package White with Indigo Blue', '/images/minigt/1564.JPG'),
(1, 'Porsche 911 (992) GT3 RS Tribute to Carrera RS Package', '/images/minigt/1515.JPG'),
(1, 'Porsche 911 Dakar Rallye Design Package White/Gentian Blue Metallic', '/images/minigt/1500.JPG'),
(1, 'Porsche 911 GT3 R #28 HubAuto Racing  2023 FIA GT World Cup 70th Macau Grand Prix', '/images/minigt/1499.JPG'),
(1, 'Porsche 911 1964 Slate Grey', '/images/minigt/1485.JPG'),
(1, 'Porsche 911 Carrera RS 2.7 Grand Prix White with Green Livery', '/images/minigt/1481.JPG'),
(1, 'Porsche 911 GT3 R #27 HubAuto Racing  2023 FIA GT World Cup 70th Macau Grand Prix', '/images/minigt/1477.JPG'),
(1, 'Porsche 911 Dakar Shade Green Metallic', '/images/minigt/1456.JPG'),
(1, 'Porsche 911 GT3 R #9 GTD PRO  Pfaff Motorsports  IMSA 2023 Sebring 12 Hrs. Winner', '/images/minigt/1441.JPG'),
(1, 'Porsche 911 Carrera RS 2.7 Grand Prix White with Blue Livery', '/images/minigt/1437.JPG'),
(1, 'Porsche 911 (992) GT3 Touring Black', '/images/minigt/1431.JPG'),
(1, 'Porsche 911 GT3 R #80 GTD AO Racing 2023  IMSA  Sebring 12 Hrs', '/images/minigt/1383.JPG'),
(1, 'Porsche 911 (992) GT3 Touring Crayon', '/images/minigt/1382.JPG'),
(1, 'Porsche 963 Porsche Penske Motorsport  2023 24 Hrs of Le Mans   Limited Edition 3000 Sets', '/images/minigt/1373.JPG'),
(1, 'Porsche 963 #75 Porsche Penske Motorsport  2023 24 Hrs of Le Mans', '/images/minigt/1370.JPG'),
(1, 'Porsche 901 1963 Signal Red', '/images/minigt/1369.JPG'),
(1, 'Porsche 911 Turbo S Safety Car 2023 IMSA Daytona 24 Hrs', '/images/minigt/1361.JPG'),
(1, 'Porsche 911 (992) GT3 RS Weissach Package White with Pyro Red', '/images/minigt/1324.JPG'),
(1, 'Porsche 911 (992) Carrera S Safety Car  2023 IMSA Daytona 24 Hrs', '/images/minigt/1308.JPG'),
(1, 'Porsche 901 1963 ''Quickblau''', '/images/minigt/1300.JPG'),
(1, 'Porsche 911 Carrera RS 2.7 Black with Red Livery', '/images/minigt/1287.JPG'),
(1, 'Porsche 911 (992) GT3 RS Black with Pyro Red', '/images/minigt/1258.JPG'),
(1, 'Porsche 911 (992) GT3 Guards Red', '/images/minigt/1233.JPG'),
(1, 'Porsche 901 1963 Ivory', '/images/minigt/1202.JPG'),
(1, 'Porsche 911 (992) GT3 RS White  with Pyro Red Accent Package', '/images/minigt/1175.JPG'),
(1, 'Porsche 911 Carrera RS 2.7 Grand Prix White with Red Livery', '/images/minigt/1147.JPG'),
(1, 'Porsche 911 Targa 4S  Shark Blue', '/images/minigt/1145.JPG'),
(1, 'Porsche 911 (992) GT3 Racing Yellow', '/images/minigt/1062.JPG'),
(1, 'Porsche 911 1964 Irish Green', '/images/minigt/578.JPG'),
(1, 'Porsche 911 Turbo S Python Green', '/images/minigt/533.JPG'),
(1, 'Porsche 911 Targa 4S  Heritage Design Edition GT Silver Metallic', '/images/minigt/517.JPG'),
(1, 'Porsche 911 Turbo S Racing Yellow', '/images/minigt/501.JPG'),
(1, 'Porsche 911 (992) GT3 White', '/images/minigt/483.JPG'),
(1, 'Porsche 911 Targa 4S Heritage Design Edition Cherry Red', '/images/minigt/457.JPG'),
(1, 'Porsche 911 (992) Carrera S Miami Blue', '/images/minigt/435.JPG'),
(1, 'Porsche Taycan Turbo S Volcano Grey Metallic', '/images/minigt/434.JPG'),
(1, 'Porsche 911 (992) GT3 Touring Gentian Blue Metallic', '/images/minigt/425.JPG'),
(1, 'Porsche 911 Turbo S Guards Red', '/images/minigt/421.JPG'),
(1, 'Porsche 911 Targa 4S Gentian Blue Metallic', '/images/minigt/412.JPG'),
(1, 'Porsche 911(991) GT2 RS Weissach Package Black', '/images/minigt/400.JPG'),
(1, 'Porsche 911 (992) GT3 GT Silver Metallic', '/images/minigt/390.JPG'),
(1, 'Porsche 911 (992) GT3 Shark Blue', '/images/minigt/379.JPG'),
(1, 'Porsche 911 (992) Carrera S White', '/images/minigt/378.JPG'),
(1, 'Porsche 911 (992) GT3 Touring Agate Grey Metallic', '/images/minigt/371.JPG'),
(1, 'Porsche 911 (992) Carrera 4S Lava Orange', '/images/minigt/369.JPG'),
(1, 'Porsche 911 Turbo S GT Silver Metallic', '/images/minigt/346.JPG'),
(1, 'Porsche 911(991) GT2 RS  Weissach Package Miami Blue', '/images/minigt/337.JPG'),
(1, 'Porsche Taycan Turbo S Gentian Blue Metallic', '/images/minigt/331.JPG'),
(1, 'Porsche 911 Targa 4S White', '/images/minigt/315.JPG'),
(1, 'Porsche 911 (992) Carrera 4S GT Silver Metallic', '/images/minigt/281.JPG'),
(1, 'Porsche Taycan Turbo S Carmine Red', '/images/minigt/265.JPG'),
(1, 'Porsche 911 (992) Carrera S Guards Red', '/images/minigt/257.JPG'),
(1, 'Porsche 911 Carrera 4S  Racing Yellow', '/images/minigt/235.JPG'),
(1, 'Porsche Taycan Turbo S Frozen Blue Metallic', '/images/minigt/209.JPG'),
(1, 'Porsche Taycan Turbo S White', '/images/minigt/197.JPG'),
(1, 'Porsche 911 (992) Carrera S GT Silver Metallic', '/images/minigt/188.JPG'),
(1, 'Porsche 911 GT2 RS  Racing Yellow', '/images/minigt/134.JPG'),
(1, 'Porsche 911 GT2 RS Weissach Package  White', '/images/minigt/103.JPG'),
(1, 'Porsche 911 GT2 RS Weissach Package  GT Silver Metallic', '/images/minigt/12.JPG'),
(1, 'Figurine: NISMO Technician Team', '/images/minigt/1522.JPG'),
(1, 'Diorama: NISSAN MOTORSPORTS & CUSTOMIZING CO.,LTD.  NISMO OPERATION', '/images/minigt/1521.JPG'),
(1, 'Figurine:  Car Enthusiasts', '/images/minigt/1508.JPG'),
(1, 'Car Hauler Trailer Type C White', '/images/minigt/1387.JPG'),
(1, 'Paddock Service Tent Set - ADVAN', '/images/minigt/1372.JPG'),
(1, '1/64 Figurine: UPS Driver and workers', '/images/minigt/1329.JPG'),
(1, 'Pitstop Base', '/images/minigt/1291.JPG'),
(1, 'Dry Container 40'' "Hapag-Lloyd"', '/images/minigt/1140.JPG'),
(1, 'Car Hauler Trailer Black', '/images/minigt/1072.JPG'),
(1, 'Paddock Service Tent Set - Martini Racing', '/images/minigt/573.JPG'),
(1, 'Figurine: Martini Racing  WRC', '/images/minigt/572.JPG'),
(1, 'Figurine: Mobile Brigade Corps (Brimob)', '/images/minigt/535.JPG'),
(1, 'Metal Figurine: Camel Trophy Crew', '/images/minigt/460.JPG'),
(1, 'Car Hauler Trailer  Type A  Silver', '/images/minigt/325.JPG'),
(1, '5" Display Turntable  Black w/ Mirror Surface', '/images/minigt/174.JPG'),
(1, 'Parking Lot Pad Type B', '/images/minigt/140.JPG'),
(1, 'Dry Container 40'' Blue', '/images/minigt/92.JPG'),
(1, 'Dry Container 40''', '/images/minigt/90.JPG'),
(1, 'LB★Works Mr. Kato & Show Girls Type B', '/images/minigt/62.JPG'),
(1, 'LB★Works Mr. Kato & Show Girls Type A', '/images/minigt/61.JPG'),
(1, 'Parking Lot Pad Type A', '/images/minigt/10.JPG'),
(1, 'Acrylic Display Case - Small', '/images/minigt/7.JPG'),
(1, 'Acrylic Display Case - Large', '/images/minigt/6.JPG'),
(1, 'Lamborghini Countach 25th Anniversary Red', '/images/minigt/2096.JPG'),
(1, 'Lamborghini Revuelto Verde Gea Matte', '/images/minigt/2094.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #45 No. 45 DEX Imaging  2024 IMSA Daytona 24 Hrs', '/images/minigt/2018.JPG'),
(1, 'Lamborghini Countach 25th Anniversary White', '/images/minigt/1943.JPG'),
(1, 'Lamborghini Revuelto Viola 30th Matte', '/images/minigt/1920.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #78 Forte Racing 2024 IMSA Daytona 24 Hrs', '/images/minigt/1840.JPG'),
(1, 'Lamborghini Revuelto Verde Selvans', '/images/minigt/1718.JPG'),
(1, 'Lamborghini Countach LPI 800-4 Verde Medio', '/images/minigt/1701.JPG'),
(1, 'Lamborghini Huracán STO  Bianco Asopo', '/images/minigt/1635.JPG'),
(1, 'Lamborghini Aventador SVJ 63 Roadster  Verde Shock', '/images/minigt/1626.JPG'),
(1, 'Lamborghini Revuelto Giallo', '/images/minigt/1607.JPG'),
(1, 'Lamborghini Countach LPI 800-4 Viola 30th', '/images/minigt/1568.JPG'),
(1, 'Lamborghini Aventador SVJ 63  Bianco Asopo', '/images/minigt/1551.JPG'),
(1, 'Lamborghini SC63 #63 Iron Lynx 2024 IMSA Sebring 12 Hrs', '/images/minigt/1511.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #63 Iron Lynx  IMSA 2023  Daytona 24 Hrs', '/images/minigt/1507.JPG'),
(1, 'Lamborghini Huracán Sterrato Blu Aegir', '/images/minigt/1502.JPG'),
(1, 'Lamborghini Aventador SVJ 63 Roadster   Nero Aldebaran', '/images/minigt/1498.JPG'),
(1, 'Lamborghini Aventador SVJ 63  Blu Aegir', '/images/minigt/1484.JPG'),
(1, 'Lamborghini  Huracán Sterrato Verde Gea Matt', '/images/minigt/1454.JPG'),
(1, 'Lamborghini Revuelto  Arancio Dac Lucido', '/images/minigt/1448.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 #83 Iron Dames  2023 IMSA  Daytona 24 Hrs', '/images/minigt/1446.JPG'),
(1, 'Lamborghini Urus Performante  Rosso Mars', '/images/minigt/1432.JPG'),
(1, 'Lamborghini Huracán Sterrato Bianco Asopo', '/images/minigt/1429.JPG'),
(1, 'Lamborghini Revuelto Blu Eleos', '/images/minigt/1418.JPG'),
(1, 'Lamborghini Urus Performante Grigio Nimbus', '/images/minigt/1417.JPG'),
(1, 'Lamborghini Huracán STO Viola Pasifae', '/images/minigt/1381.JPG'),
(1, 'Lamborghini Countach LPI 800-4  New Giallo Orion', '/images/minigt/1359.JPG'),
(1, 'Lamborghini Countach LPI 800-4  Rosso Mars', '/images/minigt/1326.JPG'),
(1, 'Lamborghini Huracán GT3 EVO2 Presentation', '/images/minigt/1286.JPG'),
(1, 'Lamborghini Urus  2022 Macau GP Official Safety Car', '/images/minigt/1267.JPG'),
(1, 'Lamborghini Huracán GT3 EVO #4  2022 Macau GP  Macau GT Cup 3rd Place', '/images/minigt/1205.JPG'),
(1, 'Lamborghini Huracán STO Nero Noctis', '/images/minigt/1195.JPG'),
(1, 'Lamborghini LB-Silhouette WORKS Aventador GT EVO Lime', '/images/minigt/1144.JPG'),
(1, 'Lamborghini Countach LPI 800-4  Nero Maia', '/images/minigt/1134.JPG'),
(1, 'Lamborghini Sián FKP 37 Blu Aegir', '/images/minigt/1074.JPG'),
(1, 'Lamborghini Aventador SVJ Giallo Orion', '/images/minigt/581.JPG'),
(1, 'Lamborghini Huracán GT3 EVO #19 GEAR Racing 2020 IMSA Daytona 24 Hrs', '/images/minigt/563.JPG'),
(1, 'Lamborghini Huracán STO  Verde Citrea', '/images/minigt/552.JPG'),
(1, 'Lamborghini Sián FKP 37  Presentation', '/images/minigt/538.JPG'),
(1, 'Lamborghini Huracán STO  Arancio Borealis', '/images/minigt/524.JPG'),
(1, 'Lamborghini Aventador SVJ Roadster Rosso Efesto', '/images/minigt/516.JPG'),
(1, 'Lamborghini Huracán GT3 EVO #39 2022 IMSA  Road America  2nd Place', '/images/minigt/503.JPG'),
(1, 'Lamborghini Huracán STO Blu Laufey', '/images/minigt/480.JPG'),
(1, 'Lamborghini Aventador SVJ Roadster Grigio Telesto', '/images/minigt/422.JPG'),
(1, 'Lamborghini Huracán EVO Bologna Airport 2020 Follow-Me Car', '/images/minigt/405.JPG'),
(1, 'Lamborghini Aventador SVJ Verde Mantis', '/images/minigt/391.JPG'),
(1, 'Lamborghini Aventador SVJ Roadster Oro Elios', '/images/minigt/360.JPG'),
(1, 'Lamborghini Urus Arancio Borealis', '/images/minigt/356.JPG'),
(1, 'Lamborghini Huracán GT3 EVO Presentation', '/images/minigt/344.JPG'),
(1, 'Lamborghini Aventador SVJ Viola Aletheia', '/images/minigt/335.JPG'),
(1, 'Lamborghini Huracán EVO Verde Mantis', '/images/minigt/308.JPG'),
(1, 'Lamborghini Huracán EVO Blu Eleos', '/images/minigt/212.JPG'),
(1, 'Lamborghini Aventador SVJ Roadster Bianco Canopus', '/images/minigt/208.JPG'),
(1, 'Lamborghini Urus  Bianco Monocerus Matt w/ Roof Box', '/images/minigt/199.JPG'),
(1, 'Lamborghini Aventador SVJ Rosso Mars', '/images/minigt/179.JPG'),
(1, 'Lamborghini Urus  Blu Eleos w/ Roof Box', '/images/minigt/154.JPG'),
(1, 'Lamborghini Urus - Giallo Auge', '/images/minigt/121.JPG'),
(1, 'Lamborghini Huracán EVO - Rosso Mars', '/images/minigt/99.JPG'),
(1, 'Lamborghini Huracan EVO Arancio Borealis', '/images/minigt/96.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Matsukiyo KOKU 3 Rotor NA-7 TAS 2025 Best Tuned Car Award', '/images/minigt/2125.JPG'),
(1, 'Mazda RX-7 LB-Super Silhouette FD-NILES', '/images/minigt/2120.JPG'),
(1, 'Volkswagen ID.Buzz Candy White/ Pomelo Yellow', '/images/minigt/2119.JPG'),
(1, 'Lotus Esprit Turbo Copper Fire Metallic "For Your Eyes Only"', '/images/minigt/2118.JPG'),
(1, 'Mazda RX-7 RE-Amemiya 2025 D1GP', '/images/minigt/2099.JPG'),
(1, 'Oracle Red Bull Racing RB19 #1  Max Verstappen  2023 F1  2023 Las Vegas GP Winner', '/images/minigt/2098.JPG'),
(1, 'Toleman TG184 #20 Johnny Cecotto 1984 Monaco Grand Prix', '/images/minigt/2097.JPG'),
(1, 'Volkswagen T1 Microbus Mizu Design', '/images/minigt/2095.JPG'),
(1, 'Nissan Skyline GT-R Top Secret VR32  Stealth Grey', '/images/minigt/2084.JPG'),
(1, 'Lotus Esprit Turbo White "For Your Eyes Only"', '/images/minigt/2070.JPG'),
(1, 'Mercedes-Benz 190 E 2.3-16 #11 Ayrton Senna 1984 Nürburgring Race of Champions w/ Figure', '/images/minigt/2068.JPG'),
(1, 'Ford Puma Rally1 #55 M-Sport Ford WRT 2025 Rally Monte-Carlo', '/images/minigt/2064.JPG'),
(1, 'Ford Mustang Mach 1 Grabber Blue', '/images/minigt/2063.JPG'),
(1, 'Bugatti W16 Mistral Yellow', '/images/minigt/2062.JPG'),
(1, 'Lotus Esprit Turbo Metallic Silver', '/images/minigt/2046.JPG'),
(1, 'Ford Mustang Mach 1 "Diamonds Are Forever"', '/images/minigt/2045.JPG'),
(1, 'Aston Martin DBS  “No Time To Die”', '/images/minigt/2044.JPG'),
(1, 'Subaru Impreza WRC97 #1  1999 DRM Champion', '/images/minigt/2019.JPG'),
(1, 'Ford Mustang GTD Spirit of America', '/images/minigt/2014.JPG'),
(1, 'Nissan Z VeilSide FFZ400 Seiran Blue', '/images/minigt/2001.JPG'),
(1, 'Ford Mustang Convertible 1964 Highland Green', '/images/minigt/2000.JPG'),
(1, 'Bentley Batur Scarab Green', '/images/minigt/1995.JPG'),
(1, 'Nissan Skyline GT-R Dark Metal Gray  (NISMO BNR34 CRS Version)', '/images/minigt/1994.JPG'),
(1, 'Volkswagen ID.Buzz KW/BBS', '/images/minigt/1993.JPG'),
(1, 'Lotus 99T #11 Satoru Nakajima 1987 Monaco Grand Prix', '/images/minigt/1984.JPG'),
(1, 'Range Rover 1981 Camel Trophy Sumatra C.Swoboda & K.Mentel   Winner', '/images/minigt/1980.JPG'),
(1, 'Bugatti Bolide Red', '/images/minigt/1979.JPG'),
(1, 'Ford Mustang Dark Horse  2024 Grabber Blue', '/images/minigt/1974.JPG'),
(1, 'Ford Mustang Mach1 Grabber Yellow', '/images/minigt/1973.JPG'),
(1, 'Mazda RX-7 RE-Amemiya Silver Metallic', '/images/minigt/1971.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione #1 1993 Rallye Monte-Carlo', '/images/minigt/1940.JPG'),
(1, 'Shelby GT500 Dragon Snake Concept Black/Gold', '/images/minigt/1939.JPG'),
(1, 'NISSAN Skyline GT-R Dark Metal Gray  (NISMO BCNR33 CRS Version)', '/images/minigt/1938.JPG'),
(1, 'Toleman TG184 #19 Ayrton Senna 1984 Monaco Grand Prix 2nd Place', '/images/minigt/1928.JPG'),
(1, 'Lotus 99T #12 Ayrton Senna 1987 Monaco Grand Prix Winner', '/images/minigt/1926.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #37 1995 SE Asia Touring Car Championship', '/images/minigt/1924.JPG'),
(1, 'Ford Mustang Mach1 1971 Race Red', '/images/minigt/1921.JPG'),
(1, 'Nissan Silvia (S15) D-MAX  #46  D-MAX Racing  2023 D1 Grand Prix', '/images/minigt/1917.JPG'),
(1, 'NISSAN GT-R 2013 Dark Metal Gray (NISMO R35 CRS Version)', '/images/minigt/1864.JPG'),
(1, 'Lancia Stratos HF #4 1978 Rally Sanremo Winner', '/images/minigt/1861.JPG'),
(1, 'Subaru Impreza WRC99 #23  2000 Acropolis Rally', '/images/minigt/1857.JPG'),
(1, 'Jaguar C-X75 Black', '/images/minigt/1854.JPG'),
(1, 'Nissan Skyline GT-R (R32) VeilSide Combat C-I White', '/images/minigt/1851.JPG'),
(1, 'Bugatti Bolide Presentation', '/images/minigt/1850.JPG'),
(1, 'Ford Puma Rally1 #16 M-Sport Ford WRT 2024 Rally Finland  3rd Place', '/images/minigt/1848.JPG'),
(1, 'Mazda Miata MX-5 (NA) Tuned Version Dark Blue', '/images/minigt/1841.JPG'),
(1, 'Volkswagen ID.Buzz Candy White / Energetic Orange', '/images/minigt/1839.JPG'),
(1, 'Bugatti W16 Mistral Black', '/images/minigt/1837.JPG'),
(1, 'Mazda RX-7 VeilSide Fortune Grey', '/images/minigt/1836.JPG'),
(1, 'Aston Martin DBS Hyper Red', '/images/minigt/1835.JPG'),
(1, 'Mazda RX-7 (FD3S) Itosyoukai Rei-gouki with RE Amemiya', '/images/minigt/1821.JPG'),
(1, 'Nissan Skyline GT-R (R34)  V-Spec II Nür  Millenium Jade', '/images/minigt/1806.JPG'),
(1, 'Bugatti EB110 Super Sport Grigio Scuro', '/images/minigt/1805.JPG'),
(1, 'Aston Martin AMR24 #18 Lance Stroll 2024 F1 2024 Bahrain GP', '/images/minigt/1804.JPG'),
(1, 'Aston Martin AMR24 #14 Fernando Alonso 2024 F1 2024 Bahrain GP', '/images/minigt/1803.JPG'),
(1, 'Bentley Flying Spur Orange Flame / Onyx', '/images/minigt/1801.JPG'),
(1, 'Lancia Stratos HF #4 1979 Spanish Rally Champion', '/images/minigt/1781.JPG'),
(1, 'Kick Sauber C44 #77  Valtteri Bottas 2024 F1 2024 Chinese GP', '/images/minigt/1780.JPG'),
(1, 'Kick Sauber C44 #24 Guanyu Zhou  2024 F1 2024 Chinese GP', '/images/minigt/1779.JPG'),
(1, 'Mazda RX-7 RE-Amemiya 20B NA 3ROTOR-7  “Ama-san Go”', '/images/minigt/1777.JPG'),
(1, 'Nissan GT-R Nismo 2024 Brilliant White Pearl', '/images/minigt/1776.JPG'),
(1, 'Aston Martin DBS 007 Edition', '/images/minigt/1771.JPG'),
(1, 'RB VCARB 01 #22 Yuki Tsunoda  2024 F1 2024 Bahrain GP', '/images/minigt/1770.JPG'),
(1, 'RB VCARB 01 #3 Daniel Ricciardo 2024 F1 2024 Bahrain GP', '/images/minigt/1769.JPG'),
(1, 'Cadillac V-Series.R #01 Cadillac Racing  2024 IMSA Sebring 12 Hrs', '/images/minigt/1767.JPG'),
(1, 'Nissan Skyline GT-R (R32) VeilSide Combat C-I Gem Red', '/images/minigt/1766.JPG'),
(1, 'Ford Mustang Dark Horse  2024 Carbonized Gray', '/images/minigt/1765.JPG'),
(1, 'Nissan Z Pandem Seiran Blue', '/images/minigt/1455.JPG'),
(1, 'Nissan Z Pandem Ikazuchi Yellow', '/images/minigt/1420.JPG'),
(1, 'Nissan Z Pandem Passion Red', '/images/minigt/1328.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Chrome Orange MINI GT GIVE 2023 USA Limited 25 pcs', '/images/minigt/1276.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Bronze Yellow', '/images/minigt/1203.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Black Pearl', '/images/minigt/1131.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Red', '/images/minigt/537.JPG'),
(1, 'Nissan Silvia (S15) Rocket Bunny  Green RHD', '/images/minigt/507.JPG'),
(1, 'Pandem Nissan GT-R (R35) Duck Tail Metallic Yellow w/ Carbon', '/images/minigt/139.JPG'),
(1, 'Pandem Nissan GT-R (R35) GT Wing  Cosmopolitan Yellow', '/images/minigt/123.JPG'),
(1, 'Pandem Nissan GT-R GT Wing  Passion Pink', '/images/minigt/97.JPG'),
(1, 'Pandem Nissan GT-R (R35) Velocity Blue', '/images/minigt/74.JPG'),
(1, 'Pandem Nissan GT-R (R35) Lava Red', '/images/minigt/73.JPG'),
(1, 'Bentley Batur Bonneville Pearl', '/images/minigt/1695.JPG'),
(1, 'Bentley Flying Spur Monaco Yellow', '/images/minigt/1641.JPG'),
(1, 'Bentley Flying Spur White Sand Verdant', '/images/minigt/1570.JPG'),
(1, 'Bentley Mulliner Bacalar 2023 Christmas Edition  ​Limited 9999 pieces', '/images/minigt/1274.JPG'),
(1, 'Bentley Mulliner Bacalar Car Zero', '/images/minigt/549.JPG'),
(1, 'Bentley Flying Spur V8  "Unifying Spur"', '/images/minigt/515.JPG'),
(1, 'Bentley Mulliner Bacalar Scarab', '/images/minigt/495.JPG'),
(1, 'Bentley Continental GT Speed 2022 Apple Green', '/images/minigt/476.JPG'),
(1, 'Bentley Continental GT Speed Anthracite Satin', '/images/minigt/446.JPG'),
(1, 'Bentley Continental GT Speed 2022 Candy Red', '/images/minigt/418.JPG'),
(1, 'Bentley Mulliner Bacalar Yellow Flame', '/images/minigt/406.JPG'),
(1, 'Bentley Flying Spur Neptune', '/images/minigt/353.JPG'),
(1, 'Bentley Continental GT3 #11 2020 Total 24 Hrs of Spa', '/images/minigt/321.JPG'),
(1, 'Bentley Flying Spur Verdant', '/images/minigt/304.JPG'),
(1, 'Bentley Continental GT3 #7 2020 Intercontinental GT Challenge Kyalami 9 Hrs', '/images/minigt/289.JPG'),
(1, 'Bentley Continental GT3 #5  2018 Blancpain GT Asia', '/images/minigt/246.JPG'),
(1, 'Bentley Continental GT  2020 GP Ice Race', '/images/minigt/226.JPG'),
(1, 'Bentley Continental GT3 #7 2020 Liqui-Moly Bathurst 12 Hrs Winner', '/images/minigt/223.JPG'),
(1, 'Bentley Continental GT St James Red', '/images/minigt/194.JPG'),
(1, 'Bentley Continental GT3 #107 M-Sport Team Bentley  2019 Total 24 Hours of Spa', '/images/minigt/186.JPG'),
(1, 'Bentley Continental GT3 #110 2019 Total 24 Hours of Spa', '/images/minigt/180.JPG'),
(1, 'Bentley Continental GT3 Christmas Edition 2020', '/images/minigt/173.JPG'),
(1, 'Bentley Continental GT3 Test Car', '/images/minigt/159.JPG'),
(1, 'Bentley Continental GT3 2018 Presentation Car', '/images/minigt/158.JPG'),
(1, 'Bentley Continental GT  Limited Edition by Mulliner', '/images/minigt/145.JPG'),
(1, 'Bentley Continental GT  2019 Pikes Peak International Hill Climb', '/images/minigt/144.JPG'),
(1, 'Bentley Continental GT Passion Pink', '/images/minigt/130.JPG'),
(1, 'Bentley Continental GT Orange Flame', '/images/minigt/101.JPG'),
(1, 'Bentley Continental GT 2018  Sequin Blue', '/images/minigt/76.JPG'),
(1, 'Range Rover 1971 International Hillrally Winner', '/images/minigt/1651.JPG'),
(1, 'Land Rover Defender 110  1989 Camel Trophy Amazon Team Japan', '/images/minigt/1419.JPG'),
(1, 'Range Rover Davos White', '/images/minigt/1390.JPG'),
(1, 'Land Rover Defender 110 1985 County Station Wagon Russet Brown', '/images/minigt/1360.JPG'),
(1, 'Land Rover Defender 110 1985 County Station Wagon Trident Green', '/images/minigt/1122.JPG'),
(1, 'Land Rover Defender 90 Pickup Masai Red', '/images/minigt/1073.JPG'),
(1, 'Land Rover Defender 110 1991 Safari Rally Martini Racing Support Vehicle', '/images/minigt/574.JPG'),
(1, 'Range Rover 1971 British Trans-Americas Expedition (VXC-868K)', '/images/minigt/547.JPG'),
(1, 'Range Rover 1982 Camel Trophy Papua New Guinea Set', '/images/minigt/521.JPG'),
(1, 'Range Rover 1971 Bahama Gold', '/images/minigt/499.JPG'),
(1, 'Land Rover Defender 90 Pickup Bronze Green', '/images/minigt/472.JPG'),
(1, 'Land Rover Defender 110 1989 Camel Trophy Amazon Team France', '/images/minigt/459.JPG'),
(1, 'Land Rover Defender 90 Wagon White', '/images/minigt/376.JPG'),
(1, 'Land Rover Defender 90 County Wagon Stratos Blue', '/images/minigt/345.JPG'),
(1, 'Land Rover Defender 90 Pickup White', '/images/minigt/324.JPG'),
(1, 'Land Rover Defender 90 Pickup - 2021 Christmas Edition', '/images/minigt/237.JPG'),
(1, 'Land Rover Defender 110 Team UK 1989 Camel Trophy Winner RHD  Dirty Version', '/images/minigt/200.JPG'),
(1, 'Land Rover Defender 110 UK Royal Mail Post Bus', '/images/minigt/163.JPG'),
(1, 'Land Rover Defender 110  1985 County Station Wagon Grey', '/images/minigt/146.JPG'),
(1, 'Land Rover Defender 110  Light Blue w/ Surfboard', '/images/minigt/95.JPG'),
(1, 'Land Rover Defender 110 Red Bull LUKA', '/images/minigt/88.JPG'),
(1, 'Land Rover Defender 110  1989 Camel Trophy Winner', '/images/minigt/87.JPG'),
(1, '1984 Nürburgring Race of Champions Set Limited Edition 5000 Sets', '/images/minigt/1807.JPG'),
(1, 'Mercedes-Maybach S 680 Black', '/images/minigt/1702.JPG'),
(1, 'Mercedes-Maybach S 680 Gold / Dark Red Metallic', '/images/minigt/1654.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II Astral Silver', '/images/minigt/1553.JPG'),
(1, 'Mercedes-Benz Actros  w/ Racing Transporter "ADVAN"', '/images/minigt/1371.JPG'),
(1, 'Mercedes-Benz Actros  w/ 40 Ft Container  " UPS Europe"', '/images/minigt/1330.JPG'),
(1, 'Mercedes-Benz EQS 580 4MATIC  Black', '/images/minigt/1323.JPG'),
(1, 'Mercedes-Maybach S680 Champagne Metallic', '/images/minigt/1133.JPG'),
(1, 'Mercedes-Benz EQS 580 4MATIC Nautical Blue Metallic', '/images/minigt/577.JPG'),
(1, 'Mercedes-Maybach S680 Cirrus Silver / Nautical Blue Metallic', '/images/minigt/529.JPG'),
(1, 'Mercedes-Benz EQS 580 4MATIC Silver Metallic', '/images/minigt/519.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II 1991 Macau Guia Race of Macau AMG/Zung Fu 3 Cars Set', '/images/minigt/497.JPG'),
(1, 'Mercedes-Benz Actros w/ Racing Transporter', '/images/minigt/469.JPG'),
(1, 'Mercedes-Benz 190E 2.5 16 Evolution II 1991 DTM #78 Lohr', '/images/minigt/402.JPG'),
(1, 'Mercedes-Benz 190E 2.5 16 Evolution II 1991 DTM Zakspeed #20 Michael Schumacher', '/images/minigt/364.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #65  AMG Motorenbau 1990 DTM', '/images/minigt/334.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #7 AMG-Mercedes 1990 DTM', '/images/minigt/293.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #7', '/images/minigt/224.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #5', '/images/minigt/172.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II #3', '/images/minigt/164.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II DTM  Silver', '/images/minigt/152.JPG'),
(1, 'Mercedes-Benz 190E 2.5-16 Evolution II  Black Pearl Metallic', '/images/minigt/151.JPG'),
(1, 'Mercedes-Benz Actros  Silver w/ Black Mercedes Logo', '/images/minigt/115.JPG'),
(1, 'Mercedes-Benz Actros  Black w/ Silver Mercedes Logo', '/images/minigt/114.JPG'),
(1, 'Mercedes-Benz Actros  Yellow w/Car Carrier', '/images/minigt/110.JPG'),
(1, 'Mercedes-Benz Actros w/ car carrier trailer', '/images/minigt/89.JPG'),
(1, 'Nissan Skyline GT-R  (NISMO BNR32 CRS Version) Dark Metal Gray', '/images/minigt/1747.JPG'),
(1, 'Nissan Z VeilSide FFZ400 Orange', '/images/minigt/1741.JPG'),
(1, 'Nissan Z VeilSide FFZ400 Gold Chrome', '/images/minigt/1707.JPG'),
(1, 'Nissan Skyline GT-R (R32) Veilside Combat C-I Veilside Combat Grey', '/images/minigt/1697.JPG'),
(1, 'Nissan LB-ER34 Super Silhouette SKYLINE Red/Black', '/images/minigt/1678.JPG'),
(1, 'Nissan GT-R NISMO #23 "MOTUL AUTECH GT-R 2021" SUPER GT SERIES Suzuka winner W/ Matsuda Figure Tsugio Matsuda Collection No.2', '/images/minigt/1636.JPG'),
(1, 'Nissan Silvia (S15)  Top Secret D1GP', '/images/minigt/1625.JPG'),
(1, 'Nissan Z GT500 #3 "Niterra MOTUL Z" NDDP RACING  2023 SUPER GT SERIES', '/images/minigt/1593.JPG'),
(1, 'Nissan Skyline GT-R (R32) Gunmetal  W/ Matsuda Figure   Tsugio Matsuda Collection', '/images/minigt/1572.JPG'),
(1, 'Nissan GT-R Nismo 2024 NISMO Stealth Gray', '/images/minigt/1571.JPG'),
(1, 'Nissan Z LB★NATION WORKS Ikazuchi Yellow', '/images/minigt/1514.JPG'),
(1, 'Nissan GT-R NISMO GT3 #23 KCMG 2018 FIA GT World Cup Macau', '/images/minigt/1496.JPG'),
(1, 'Nissan Skyline GT-R (R34)  V-Spec Active Red', '/images/minigt/1480.JPG'),
(1, 'Nissan Skyline GT-R (R34)  V-Spec Bayside Blue', '/images/minigt/1451.JPG'),
(1, 'Nissan Skyline GT-R (R34)  V-Spec  Lightning Yellow', '/images/minigt/1428.JPG'),
(1, 'Nissan  Skyline Kenmeri Liberty Walk Matt Black', '/images/minigt/1388.JPG'),
(1, 'Nissan Skyline GT-R (R34) Tommykaira R-z Millenium Jade', '/images/minigt/1306.JPG'),
(1, 'Datsun 510 Pro Street  Full Carbon V1', '/images/minigt/1290.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works  (Greddy) Chrome plated - Maui Charity Limited 25 pieces', '/images/minigt/1275.JPG'),
(1, 'Nissan Skyline GT-R (R32) Gr. A #23 1990 Macau Guia Race Winner', '/images/minigt/1268.JPG'),
(1, 'Datsun Street 510 Racing V1', '/images/minigt/1244.JPG'),
(1, 'Nissan Fairlady Z Kaido GT ''ORANGE BANG'' Larry Chen V1', '/images/minigt/1242.JPG'),
(1, 'Nissan Skyline GT-R (R33) DAI33 V1', '/images/minigt/1228.JPG'),
(1, 'Nissan Skyline GT-R (R34) Tommykaira R-z Midnight Purple', '/images/minigt/1164.JPG'),
(1, 'Nissan Skyline GT-R (R33) Kaido Works V2', '/images/minigt/1148.JPG'),
(1, 'Nissan Z Performance 2023 Everest White', '/images/minigt/1129.JPG'),
(1, 'Nissan Fairlady Z Version ST 2023 Everest White', '/images/minigt/1128.JPG'),
(1, 'Datsun 510 Pro Street JPN V1', '/images/minigt/1125.JPG'),
(1, 'Nissan Skyline GT-R (R33) Kaido Works V1', '/images/minigt/1123.JPG'),
(1, 'Nissan Skyline GT-R Top Secret  VR32 Metallic Blue', '/images/minigt/1121.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works GReddy V1', '/images/minigt/1105.JPG'),
(1, 'Datsun KAIDO Fairlady Z MOTUL  V3', '/images/minigt/1103.JPG'),
(1, 'Datsun KAIDO 510 Wagon CARBON FIBER V3', '/images/minigt/1087.JPG'),
(1, 'Nissan Skyline GT-R (R34) TAMIYA x KAIDO HOUSE "The Hornet"', '/images/minigt/1086.JPG'),
(1, 'Datsun KAIDO 510 Wagon 4x4 Winter Holiday Edition', '/images/minigt/1085.JPG'),
(1, 'Nissan Silvia S15 D-MAX  Metallic Orange', '/images/minigt/1082.JPG'),
(1, 'Nissan Silvia Top Secret (S15) Silver', '/images/minigt/550.JPG'),
(1, 'Nissan GT-R (R34) Tommykaira R-z Red', '/images/minigt/548.JPG'),
(1, 'Nissan Skyline GT-R (R34) Top Secret Bayside Blue', '/images/minigt/540.JPG'),
(1, 'Nissan Skyline GT-R (R34) V-Spec II N1 White', '/images/minigt/508.JPG'),
(1, 'Datsun KAIDO 510 Wagon FIRE V1', '/images/minigt/504.JPG'),
(1, 'Datsun KAIDO 510 Wagon Kaido GT Surf Safari RS', '/images/minigt/490.JPG'),
(1, 'Nissan Skyline GT-R (R34) Top Secret 2022 Christmas Limited Edition', '/images/minigt/489.JPG'),
(1, 'Top Secret Nissan Skyline GT-R VR32 White', '/images/minigt/465.JPG'),
(1, 'Nissan Skyline GT-R (R34) V-Spec II  MINI GT Digital Camouflage Purple', '/images/minigt/456.JPG'),
(1, 'Nissan Z Performance 2023 Seiran Blue', '/images/minigt/453.JPG'),
(1, 'Nissan Fairlady Z Version ST 2023 Seiran Blue', '/images/minigt/452.JPG'),
(1, 'Nissan Z Proto Spec 2023 Ikazuchi Yellow', '/images/minigt/414.JPG'),
(1, 'Nissan Fairlady Z Proto Spec 2023 Ikazuchi Yellow', '/images/minigt/413.JPG'),
(1, 'Nissan Skyline GT-R (R34) V-Spec N1 White', '/images/minigt/398.JPG'),
(1, 'Nissan Skyline GT-R (R32) Gr. A #2 1991 Macau GP', '/images/minigt/375.JPG'),
(1, 'Datsun KAIDO 510 Wagon Hanami V2', '/images/minigt/352.JPG'),
(1, 'Datsun KAIDO 510 Wagon Hanami V1', '/images/minigt/351.JPG'),
(1, 'Nissan Skyline GT-R (R34)  M-Spec Silica Breath', '/images/minigt/341.JPG'),
(1, 'Datsun KAIDO 510 Wagon Blue', '/images/minigt/336.JPG'),
(1, 'Nissan Skyline GT-R (R34)  V-Spec II Bayside Blue', '/images/minigt/333.JPG'),
(1, 'Nissan GT-R NISMO GT3  2018  Test Car', '/images/minigt/322.JPG'),
(1, 'Audi ABT RS6-R Glacier White Metallic', '/images/minigt/1298.JPG'),
(1, 'ABT Audi RS6-R Navarra Blue Metallic', '/images/minigt/1075.JPG'),
(1, 'ABT Audi RS6 Johann Abt Signature Edition Black', '/images/minigt/527.JPG'),
(1, 'ABT Audi RS6-R Daytona Grey', '/images/minigt/484.JPG'),
(1, 'Audi RS 6 Avant Carbon Black Edition Florett Silver', '/images/minigt/370.JPG'),
(1, 'Audi RS 6 Avant Mythos Black Metallic w/ Roof Box', '/images/minigt/239.JPG'),
(1, 'Audi RS 6 Avant Carbon Black Edition Tango Red', '/images/minigt/170.JPG'),
(1, 'Audi RS 6 Avant Navarra Blue Metallic', '/images/minigt/167.JPG'),
(1, 'HKS ADVAN GR Supra', '/images/minigt/182.JPG'),
(1, 'Nissan  Skyline GT-R (R32) Gr. A #87 HKS', '/images/minigt/126.JPG'),
(1, 'Nissan Skyline GT-R R32 Gr. A #87 HKS 1992 Group A.', '/images/minigt/107.JPG'),
(1, 'Nissan Skyline GT-R (R32) KAIDO WORKS V1', '/images/minigt/2135.JPG'),
(1, 'BMW M3  Kaido Works ADVAN', '/images/minigt/2134.JPG'),
(1, 'Nissan Fairlady Z TAMIYA x KAIDO HOUSE "The FROG"  V1', '/images/minigt/2133.JPG'),
(1, 'Honda NSX Kaido Racing V1', '/images/minigt/2132.JPG'),
(1, 'Volkswagen T1 GReddy Pickup V1', '/images/minigt/2088.JPG'),
(1, 'KAIDO STAR V2', '/images/minigt/2087.JPG'),
(1, 'Nissan Silvia S13-R Circuit Spec V1', '/images/minigt/2086.JPG'),
(1, 'Nissan Skyline 2000GT-R (KPGC10) Cortez V1', '/images/minigt/2085.JPG'),
(1, 'BMW M3 KAIDO WORKS  LARRY CHEN V1', '/images/minigt/2078.JPG'),
(1, 'BMW M3  Kaido Touring Champ V1', '/images/minigt/2077.JPG'),
(1, 'Volkswagen  T1 KAIDO WORKS V1', '/images/minigt/2076.JPG'),
(1, 'Toyota AE86 Sprinter Trueno Kaido ADVAN', '/images/minigt/2075.JPG'),
(1, 'Nissan Fairlady Z Kaido GT  Police', '/images/minigt/2074.JPG'),
(1, 'Datsun 510 Street Nismo V3', '/images/minigt/2073.JPG'),
(1, 'Nissan Skyline 2000 GT-R (KPGC10) Kaido Street V2', '/images/minigt/2072.JPG'),
(1, 'Chevrolet Silverado KAIDO WORKS V3', '/images/minigt/2071.JPG'),
(1, 'Chevrolet Silverado Dually Vintage Spec V2', '/images/minigt/2047.JPG'),
(1, 'Toyota AE86 Sprinter Trueno  TOUGE V1', '/images/minigt/2006.JPG'),
(1, 'KAIDO STAR V1', '/images/minigt/2005.JPG'),
(1, 'BMW M3  Kaido Works V2', '/images/minigt/2004.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works V4', '/images/minigt/2003.JPG'),
(1, 'Nissan Skyline GT-R (R34) KAIDO RACING FACTORY V2', '/images/minigt/1989.JPG'),
(1, 'Honda NSX  TAMIYA x KAIDO HOUSE "AVANTE" V1', '/images/minigt/1988.JPG'),
(1, 'Chevrolet Silverado Dually Hot Rod V1', '/images/minigt/1987.JPG'),
(1, 'Nissan Silvia S13-R KAIDO DRIFT V1', '/images/minigt/1986.JPG'),
(1, 'Toyota AE86 Sprinter Trueno Kaido Street V2', '/images/minigt/1894.JPG'),
(1, 'BMW M3  Kaido GT V2', '/images/minigt/1893.JPG'),
(1, 'Nissan Skyline 2000GT-R (KPGC10) Kaido Works V2', '/images/minigt/1892.JPG'),
(1, 'Datsun KAIDO 510 Wagon 4x4 Kaido ISLANDS V1', '/images/minigt/1891.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works GReddy V2', '/images/minigt/1880.JPG'),
(1, 'Datsun 510 Street Team XMM V1', '/images/minigt/1879.JPG'),
(1, 'Nissan Skyline 2000GT-R (KPGC10) Kaido Street V1', '/images/minigt/1878.JPG'),
(1, 'Honda NSX Kaido Racing V2', '/images/minigt/1877.JPG'),
(1, 'BMW M3 KaidoHaus V1', '/images/minigt/1818.JPG'),
(1, 'Chevrolet Silverado KAIDO   HKS V1', '/images/minigt/1817.JPG'),
(1, 'Nissan Skyline GT-R (R34) TAMIYA x KAIDO HOUSE "The GRASSHOPPER" V1', '/images/minigt/1816.JPG'),
(1, 'Toyota AE86 Sprinter Trueno Kaido Street V1', '/images/minigt/1815.JPG'),
(1, 'Honda Civic (EF) Kaido Roulette  V1', '/images/minigt/1814.JPG'),
(1, 'Datsun KAIDO 510 Wagon OG  Flo Yellow', '/images/minigt/1813.JPG'),
(1, 'Kaido House BBS Tent V1', '/images/minigt/1812.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Star Racing V1', '/images/minigt/1811.JPG'),
(1, 'Toyota AE86 Sprinter Trueno Kaido Racing V1', '/images/minigt/1810.JPG'),
(1, 'BMW M3 Kaido KW V1', '/images/minigt/1809.JPG'),
(1, 'Datsun 510 Pro Street Buta V1', '/images/minigt/1808.JPG'),
(1, 'Nissan Skyline 2000GT-R (KPGC10) Kaido Racing V1', '/images/minigt/1775.JPG'),
(1, 'Chevrolet Silverado Dually Vintage Spec V1', '/images/minigt/1774.JPG'),
(1, 'Nissan Skyline GT-R (R33) Kaido Works ADVAN', '/images/minigt/1773.JPG'),
(1, 'Honda NSX Kaido Test Car Spec V1', '/images/minigt/1772.JPG'),
(1, 'Nissan Skyline GT-R (R33) Imai Racing V1', '/images/minigt/1684.JPG'),
(1, 'Datsun 510  4x4 Wagon Kaido Offroad V2', '/images/minigt/1683.JPG'),
(1, 'Honda NSX (NA1) Kaido WORKS V2', '/images/minigt/1682.JPG'),
(1, 'Chevrolet Silverado  “Sumatran Rhino”  KAIDO x MIZU Diecast', '/images/minigt/1615.JPG'),
(1, 'Nissan Fairlady Z Kaido GT  ADVAN', '/images/minigt/1592.JPG'),
(1, 'Nissan Skyline 2000GT-R (KPGC10)  Kaido Works V1', '/images/minigt/1591.JPG'),
(1, 'Nissan Skyline GT-R (R33) Active Carbon R V2', '/images/minigt/1590.JPG'),
(1, 'Honda Civic (EF) Kanjo  V1', '/images/minigt/1558.JPG'),
(1, 'Datsun 510 Pro Street Anniversary Edition', '/images/minigt/1557.JPG'),
(1, 'Honda NSX Evasive V2', '/images/minigt/1556.JPG'),
(1, '1/64 Figurine:  Kaido & Sons V2', '/images/minigt/1555.JPG'),
(1, 'BMW M3 (E30) Kaido GT  V1', '/images/minigt/1542.JPG'),
(1, 'Chevrolet Silverado KAIDO V2', '/images/minigt/1541.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works (V2 Aero) SHINJUKU V2', '/images/minigt/1540.JPG'),
(1, 'Chevrolet Silverado Dually on Fire V2', '/images/minigt/1520.JPG'),
(1, 'Honda Civic (EF) Kaido Works V2', '/images/minigt/1519.JPG'),
(1, 'BMW M3 (E30) Kaido Works V1', '/images/minigt/1518.JPG'),
(1, 'Chevrolet Silverado KAIDO Vintage Spec  V1', '/images/minigt/1490.JPG'),
(1, 'Datsun KAIDO 510 Wagon  HKS V1', '/images/minigt/1489.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works SHINJUKU V1', '/images/minigt/1475.JPG'),
(1, 'Chevrolet Silverado TAMIYA x KAIDO HOUSE "Clod Buster"', '/images/minigt/1424.JPG'),
(1, 'Nissan Skyline GT-R (R33) HKS V1', '/images/minigt/1423.JPG'),
(1, 'Honda Civic (EF) Kaido Works V1', '/images/minigt/1422.JPG'),
(1, 'Datsun Street 510 Racing V2', '/images/minigt/1386.JPG'),
(1, 'Nissan Skyline GT-R (R34) KAIDO RACING FACTORY V1', '/images/minigt/1385.JPG'),
(1, 'Chevrolet Silverado Dually on Fire V1', '/images/minigt/1384.JPG'),
(1, 'Datsun KAIDO 510 Wagon 4x4 Kaido Offroad V1', '/images/minigt/1365.JPG'),
(1, 'Nissan Skyline GT-R R34 Kaido Works (V2 Aero) Police', '/images/minigt/1364.JPG'),
(1, 'Honda NSX Kaido Racing V1', '/images/minigt/1363.JPG'),
(1, 'Datsun 510 Street Nismo V2', '/images/minigt/1356.JPG'),
(1, 'Nissan Fairlady Z HKS', '/images/minigt/1355.JPG'),
(1, 'Nissan Skyline GT-R (R33) Active Carbon R', '/images/minigt/1354.JPG'),
(1, 'Honda NSX Kaido WORKS V1', '/images/minigt/1289.JPG'),
(1, 'Chevrolet Silverado Dually KAIDO WORKS V2', '/images/minigt/1288.JPG'),
(1, 'Nissan Skyline GT-R (R34) Kaido Works V4', '/images/minigt/1245.JPG'),
(1, 'Kaido House GREDDY Tent V1', '/images/minigt/1243.JPG'),
(1, 'Chevrolet Silverado KAIDO WORKS V2', '/images/minigt/1229.JPG'),
(1, 'Honda NSX Evasive V1', '/images/minigt/1227.JPG'),
(1, 'Chevrolet Silverado KAIDO WORKS V1', '/images/minigt/1124.JPG'),
(1, 'Chevrolet Silverado KAIDO V1', '/images/minigt/1104.JPG'),
(1, 'Chevrolet Silverado Dually KAIDO V1', '/images/minigt/1088.JPG'),
(1, 'Datsun Street 510 Nismo V1', '/images/minigt/1084.JPG'),
(1, 'KaidoHouse Figurine: Kaido & Sons', '/images/minigt/506.JPG'),
(1, 'Datsun 510 Pro Street BRE510 V1', '/images/minigt/318.JPG'),
(1, 'Datsun 510 Pro Street SK510 Orange', '/images/minigt/270.JPG'),
(1, 'Datsun Pro Street SK510 Red', '/images/minigt/269.JPG'),
(1, 'Datsun 510 Pro Street  OG Purple', '/images/minigt/220.JPG'),
(1, 'Datsun 510 Pro Street  OG Green', '/images/minigt/219.JPG'),
(1, 'Lancia Stratos HF Stradale Nero', '/images/minigt/1681.JPG'),
(1, 'Lancia Stratos HF Stradale  Giallo Fly', '/images/minigt/1442.JPG'),
(1, 'Lancia Stratos HF Stradale Azzuro Chiaro', '/images/minigt/1416.JPG'),
(1, 'Lancia Stratos HF 1975 Rally Sanremo Winner #11', '/images/minigt/1349.JPG'),
(1, 'Lancia Stratos HF Stradale Verde Chiaro', '/images/minigt/1193.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione  1992 Rally MonteCarlo Martini Racing 4 Cars Set', '/images/minigt/576.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione 1992 Rally MonteCarlo Winner #4', '/images/minigt/575.JPG'),
(1, 'Lancia Stratos HF 1979 Rally Monte Carlo Winner #4', '/images/minigt/511.JPG'),
(1, 'Lancia Stratos HF 1977 Rally MonteCarlo Winner #1', '/images/minigt/420.JPG'),
(1, 'Lancia Stratos HF Stradale Bleu Vincennes', '/images/minigt/410.JPG'),
(1, 'Lancia Stratos HF Stradale Rosso Arancio', '/images/minigt/363.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione 1992 Rally 1000 Lakes Winner #3', '/images/minigt/305.JPG'),
(1, 'Lancia Delta HF Integrale Evoluzione Martini Racing', '/images/minigt/284.JPG'),
(1, 'Lincoln Capri Christmas Hot Rod by Tim Sadchikov  2024 Christmas Edition', '/images/minigt/1616.JPG'),
(1, 'Oracle Red Bull Racing RB19 #1  Max Verstappen  2023 F1  2023 Japanese Grand Prix Pit Crew Set', '/images/minigt/1608.JPG'),
(1, 'Ford GT LMGTE PRO   2019 24 Hrs of Le Mans Ford Chip Ganassi Team 4 Cars Set', '/images/minigt/1241.JPG'),
(1, 'Oracle Red Bull Racing RB18 #11 Sergio Pérez 2022 Abu Dhabi GP Pit Crew Set', '/images/minigt/1127.JPG'),
(1, 'Oracle Red Bull Racing RB18 #1  Max Verstappen  2022 Abu Dhabi GP Pit Crew Set', '/images/minigt/1126.JPG'),
(1, 'Ford Mustang GT3 #65 Ford Multimatic Motorsports 2024 IMSA Daytona 24 Hrs', '/images/minigt/1744.JPG'),
(1, 'Ford Puma Rally1 #13 M-Sport Ford WRT 2024 Rally Monte Carlo', '/images/minigt/1739.JPG'),
(1, 'Ford Mustang GT3 #64 Ford Multimatic Motorsports 2024 IMSA Daytona 24 Hrs', '/images/minigt/1633.JPG'),
(1, 'Ford Mustang Shelby GT500  Heritage Edition', '/images/minigt/1426.JPG'),
(1, 'Ford GT Sunoco Blue', '/images/minigt/1366.JPG'),
(1, 'Shelby GT500 Dragon Snake Concept  Fuchsia Metallic', '/images/minigt/1305.JPG'),
(1, 'Ford GT  ’64 Prototype Heritage Edition', '/images/minigt/1284.JPG'),
(1, 'FORD MUSTANG GT LB-WORKS White', '/images/minigt/1206.JPG'),
(1, 'Ford GT Triple Yellow', '/images/minigt/1171.JPG'),
(1, 'Ford GT MK II #013 Rosso Alpha', '/images/minigt/1132.JPG'),
(1, 'Ford GT Holman Moody Heritage Edition', '/images/minigt/546.JPG'),
(1, 'Ford Puma Rally1  #19  M-Sport Ford WRT 2022 Rally MonteCarlo Winner LHD', '/images/minigt/543.JPG'),
(1, 'Ford Mustang Shelby GT500 Twister Orange', '/images/minigt/512.JPG'),
(1, 'Ford GT Alan Mann Heritage Edition', '/images/minigt/481.JPG'),
(1, 'Ford GT #85 2019 24 Hrs of Le Mans LM GTE-Am', '/images/minigt/442.JPG'),
(1, 'Ford GT MK II Ford Performance', '/images/minigt/430.JPG'),
(1, 'Ford GT Mk II #002 Blue / Orange', '/images/minigt/355.JPG'),
(1, 'Ford GT Ingot Silver', '/images/minigt/332.JPG'),
(1, 'Ford Mustang Shelby GT500  Shadow Black', '/images/minigt/316.JPG'),
(1, 'Ford GT 2021 Heritage Edition', '/images/minigt/294.JPG'),
(1, 'Ford GT MK II #006 Shadow Black', '/images/minigt/273.JPG'),
(1, 'Ford Mustang Shelby GT500 Ford Performance Blue', '/images/minigt/264.JPG'),
(1, 'Ford GT MK II  2019 Goodwood Festival of Speed', '/images/minigt/253.JPG'),
(1, 'Ford GT LMGTE PRO 2016 24 Hrs of Le Mans Ford Chip Ganassi Team 4 Cars Set', '/images/minigt/252.JPG'),
(1, 'Ford GT  Liquid Blue', '/images/minigt/231.JPG'),
(1, 'Ford GT GTLM  Test Car', '/images/minigt/230.JPG'),
(1, 'Ford GT LMGTE PRO #68   2016 24 Hrs of Le Mans Class Winner', '/images/minigt/201.JPG'),
(1, 'Bugatti EB110 GT Verde Scuro', '/images/minigt/1738.JPG'),
(1, 'Bugatti EB110 Super Sport  Blu  Bugatti', '/images/minigt/1629.JPG'),
(1, 'Bugatti EB110 Super Sport Giallo Bugatti', '/images/minigt/1569.JPG'),
(1, 'Bugatti EB110 GT Dark Red Metallic', '/images/minigt/1501.JPG'),
(1, 'Bugatti Vision Gran Turismo Black', '/images/minigt/1479.JPG'),
(1, 'Bugatti EB110 GT Grigio Chiaro', '/images/minigt/1299.JPG'),
(1, 'Bugatti Divo  White', '/images/minigt/1232.JPG'),
(1, 'Bugatti EB110 GT Blu Bugatti', '/images/minigt/1204.JPG'),
(1, 'Bugatti Divo Blu Bugatti', '/images/minigt/1130.JPG'),
(1, 'Bugatti Centodieci Blu Bugatti', '/images/minigt/1120.JPG'),
(1, 'Bugatti Chiron Pur Sport  White', '/images/minigt/1068.JPG'),
(1, 'Bugatti Chiron Super Sport Gold', '/images/minigt/526.JPG'),
(1, 'Bugatti Divo  Red Metallic', '/images/minigt/510.JPG'),
(1, 'Bugatti Chiron Pur Sport', '/images/minigt/492.JPG'),
(1, 'Bugatti Divo Presentation', '/images/minigt/477.JPG'),
(1, 'Bugatti Centodieci Black', '/images/minigt/462.JPG'),
(1, 'Bugatti Chiron Super Sport White', '/images/minigt/444.JPG'),
(1, 'Bugatti Chiron Pur Sport Yellow', '/images/minigt/429.JPG'),
(1, 'Bugatti Chiron Super Sport 300+ World Record 304.773 mph', '/images/minigt/409.JPG'),
(1, 'Bugatti Chiron Pur Sport Blue', '/images/minigt/403.JPG'),
(1, 'Bugatti Chiron Super Sport 300+ Matte Black', '/images/minigt/372.JPG'),
(1, 'Bugatti Vision Gran Turismo     Silver', '/images/minigt/367.JPG'),
(1, 'Bugatti Centodieci White', '/images/minigt/323.JPG'),
(1, 'Bugatti Vision Gran Turismo Yellow', '/images/minigt/299.JPG'),
(1, 'Bugatti Vision Gran Turismo  Light Blue', '/images/minigt/248.JPG');

SELECT setval(pg_get_serial_sequence('brand_objects', 'id'), (SELECT COALESCE(MAX(id), 1) FROM brand_objects));